### ISSUE TITLE
Provide an option to autofix for common configuration issues

### ISSUE THREAD

**Issue by florianb** [sindresorhus/atom-editorconfig#105]
Things we could fix immediately:
- disable packages which are known to prevent editorconfig from working (like the unholy `whitespace`-package)
- ~~set the tabType to 'auto'~~

Prerequisites:
- [x] Allow fixing of indentation-style (done via `EditorConfig: Fix File`)

**Comment by jokeyrhyme** [comment]
> disable packages which are known to prevent editorconfig from working (like the unholy `whitespace`-package)

I would like this, too, but only if no .editorconfig file is found. For a project that is not using EditorConfig, the default `whitespace`-package should be restored.

But if .editorconfig is found, then automatically disable the `whitespace`-package.

**Comment by florianb** [comment]
I think that's the way to go. However, before we can disable it we must provide its full functionality. Which means we should be able to convert spaces to tabs and vice versa, since this is probably one of the most used functions after putting a foreign file under editorconfig.

**Comment by unluisco** [comment]
Hi,
can we have autofix to identation style?
thanks

**Comment by florianb** [comment]
Hi @unluisco this issue is dedicated to fix configuration issues. I consider fixing the identation style on save being too expensive compared to its benefit - so it is unlikely this will come.

Please use the `EditorConfig: Fix File`-command to fix the identation-style after pasting code or putting files under `.editorconfig`.

**Comment by florianb** [comment]
I decided to drop maintenance. Sorry.

See https://github.com/sindresorhus/atom-editorconfig/issues/231

**Comment by sindresorhus** [comment]
Closing as Atom is abandoned.
