### ISSUE TITLE
Multiple newline/carriage returns aren't stripped from the end of the file

### ISSUE THREAD

**Issue by florianb** [sindresorhus/atom-editorconfig#108]

**Comment by glennpratt** [comment]
This seems to be removing multiple newlines even when I have:

```
trim_trailing_whitespace = false
```

**Comment by florianb** [comment]
Hi @glennpratt, thanks for reporting this issue. Please open a new issue containing all necessary information to debug this.

Even though you would probably like to know that multiple newlines should be influenced by `insert_final_newline` only.

**Comment by glennpratt** [comment]
Thanks. #164
