### ISSUE TITLE
there is not a 🐭 in the status bar

### ISSUE THREAD

**Issue by unluisco** [sindresorhus/atom-editorconfig#110]
instead of a 🐭, there is a letter 'A'

![package json users luisco dropbox dev bicalma 2016-10-20 13-31-18](https://cloud.githubusercontent.com/assets/6332263/19573079/53185d8e-96ca-11e6-85d3-21b8dbe2b519.png)

**Comment by florianb** [comment]
Hi @unluisco -- this is very sad. We implemented the :mouse: as font which gets delivered as part of the package. It seems you are currently the only person where it doesn't work which let me assume something went wrong during the installation of the package.

To search for bugs you could open the developer console and look out for any errors addressing the fonts. But i guess it would be a god idea to reinstall the package first (`apm uninstall editorconfig; apm install editorconfig`) and have a look if this fixes it.

**Comment by scttcper** [comment]
I also had the letter 'A' along with the issue in #109 will try reinstalling.

**Comment by florianb** [comment]
Okay -- thanks for the hint @scttcper!

@unluisco may i ask you to post a list of your installed packages?

**Comment by dannyfritz** [comment]
I also have the `A`

**Comment by battaglr** [comment]
I also have the `A`. Having an option to remove this is something you guys would consider adding?

**Comment by florianb** [comment]
Thanks @dannyfritz, @battaglr -- could you please post a list of the active packages and if this is displayed wrong in every filetype you're trying to edit? Thanks in advance!

**Comment by florianb** [comment]
@dannyfritz: the mouse is implemented as font, the escape-sequence is the character-code of the symbol. It is colored after the state of editorconfig for the current file.

@battaglr: This could be considered i guess i will open a discuss-issue for that.

**Comment by torifat** [comment]
Changing `atom-editorconfig` to `editorconfig` worked for me.

```bash
$ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.1
```

```diff
@font-face {
	font-family: 'Atom Editorconfig';
-	src: url('atom://atom-editorconfig/fonts/Atom-Editorconfig.eot');
+	src: url('atom://editorconfig/fonts/Atom-Editorconfig.eot');
-	src:	url('atom://atom-editorconfig/fonts/Atom-Editorconfig.eot?#iefix') format('embedded-opentype'),
+	src:	url('atom://editorconfig/fonts/Atom-Editorconfig.eot?#iefix') format('embedded-opentype'),
-			url('atom://atom-editorconfig/fonts/Atom-Editorconfig.woff') format('woff'),
+			url('atom://editorconfig/fonts/Atom-Editorconfig.woff') format('woff'),
-			url('atom://atom-editorconfig/fonts/Atom-Editorconfig.ttf') format('truetype'),
+			url('atom://editorconfig/fonts/Atom-Editorconfig.ttf') format('truetype'),
-			url('atom://atom-editorconfig/fonts/Atom-Editorconfig.svg#Atom-Editorconfig') format('svg');
+			url('atom://editorconfig/fonts/Atom-Editorconfig.svg#Atom-Editorconfig') format('svg');
	font-weight: normal;
	font-style: normal;
}
```

**Comment by florianb** [comment]
Thank you @torifat you are right, the path is wrong - i will prepare a patch (and reduce then to a single woff, too)!

**Comment by unluisco** [comment]
that's the solution 👍 
thanks

**Comment by florianb** [comment]
I recently published 1.5.3 which should fix this issue. I'd appreciate if anybody could confirm that it's working.

**Comment by torifat** [comment]
@florianb working 👍

**Comment by florianb** [comment]
Thanks everybody and sorry for the inconveniences! 💝
