### ISSUE TITLE
Consider adding an option to hide the 🐭  in the status bar

### ISSUE THREAD

**Issue by battaglr** [sindresorhus/atom-editorconfig#111]
Sometimes the status bar can get too cluttered.

Having an option to hide the 🐭  would be great! Thanks! 😀 

---

*Previous mentions of this: https://github.com/sindresorhus/atom-editorconfig/issues/110#issuecomment-255206800 and https://github.com/sindresorhus/atom-editorconfig/issues/110#issuecomment-255209559*.

**Comment by florianb** [comment]
Thanks @battaglr!

@sindresorhus: I think it would be a good idea to introduce a config-setting for this, would you agree (i remember you had strong opinions about that)?

**Comment by sindresorhus** [comment]
Why have it there in the first place then? Is it really that essential? Couldn't it just be a command in the command-palette?

**Comment by battaglr** [comment]
That's the right question to ask, @sindresorhus. Thanks! 😉

**Comment by febLey** [comment]
I really like to have the indicator in the status bar, but it could be opt-in.
The command could be an additional feature.

**Comment by varemenos** [comment]
Even in the case where it's not removed from the status bar, why does it appear when there is no active editor?

**Comment by jbergstroem** [comment]
The reason I want to hide the icon is that this is one of those packages that Just Work™. I don't need it to tell (or show) me what's going on -- just apply whatever config there is. If I get a reason to not trust it I believe we have a bigger problem.

**Comment by florianb** [comment]
Thank you all for your questions and opinions - i am very grateful for your feedback.

I want editorconfig become a "Just Works"-package. However - it was less then unreliable (Just Don't Work :tm:) in the past and we were confronted with the results in the issue-board (for those few who made it here to leave their feedback).

The status-icon was introduced for two reasons: 1) let the people proof with one look, if the editorconfig is working and 2) use it to get some of the lost trust back by obviously showing the thing is moving forward.

I would like to have editorconfig acting in the background without any need for intervention, unfortunately this is not possible at the moment. There are a some cases where editorconfig may not work as expected. As soon as we have found to fix that i wouldn't show anything from editorconfig at all (at normal operation).

Until this is possible i tend to leave the statusbar-icon for the warning (ecfg may not work) and the error (ecfg is proven to not work) states. I agree that showing the icon in all other cases is well-meant but not necessary.

I know this does not meet all of your positions but allowing you to hide the statusbar-icon and enable it for the users is the only compromise i see to satisfy the different requirements. However we end up here, i will disable the icon for the default-states and introduce an additional editorconfig-command to invoke the notification.

**Comment by Alhadis** [comment]
You should also add an ID to the status-bar tile's top-most container element, so users have the option to hide it with CSS. E.g., add a line [here](https://github.com/sindresorhus/atom-editorconfig/blob/master/lib/statustile-view.js#L82) like `div.id = 'aec-status-bar-tile-wrap'`.

I also came here to request the same thing, BTW.

**Comment by florianb** [comment]
Hey, since there were no further arguments or ideas added, the :mouse: will only show up in failure-states after the upcoming release.

If you want to check if EditorConfig is working invoke `EditorConfig: Show State`.

Thanks everybody for your contribution. 💝 

P.s.: @Alhadis the id (`aec-status-bar-container`) is added.

**Comment by Alhadis** [comment]
Ace, thanks!
