### ISSUE TITLE
Folds lost on save

### ISSUE THREAD

**Issue by Proteo** [sindresorhus/atom-editorconfig#114]
Hi, thank you very much for this great package.

A few days back I noticed that something strange started to happen: every time I hit CMD+S (save current file) you can see a quick "flash" (the code lose its format for the fraction of a second) and any folded code gets uncollapsed.

I disabled every package I have installed in order to find out the guilty and as it turns out this happens only when Editor config is enabled. I'm sure this wasn't happening a few days ago, so I guess this is due to changes introduced in one of the recent versions.

Best regards.

**Comment by florianb** [comment]
Hi @Proteo -- thanks for that report. This should have been fixed in 1.5.4 which seems to be not deployed  properly. I will publish 1.5.5 today, i hope this fixes it. I am sorry for the inconveniences.

**Comment by Proteo** [comment]
Great @florianb! thank you very much for your quick response.

**Comment by florianb** [comment]
Hi @Proteo, @bradrich i recently published 1.6.0 -- this should fix that issue.

It could be, that if the editorconfig-plugin changes anything in a folded section, that this folded section gets widened. If this becomes a problem, please leave open an issue for that.

I would appreciate if you could check if this release solves your issue! 🍻

**Comment by Proteo** [comment]
@florianb tested 1.6.0 and it works like a charm. No more flashing/repainting and folds are respected. Thank you very much for your support!

**Comment by florianb** [comment]
Great to hear that @Proteo! Thanks! ☕️

**Comment by bradrich** [comment]
LGTM. Everything is back to normal and working wonderfully.
