### ISSUE TITLE
Optimize editorconfig-grammar

### ISSUE THREAD

**Issue by florianb** [sindresorhus/atom-editorconfig#115]
The grammar

- [ ] could be smaller
- [ ] should color literals as constants

**Comment by Alhadis** [comment]
Regarding [this](https://github.com/sindresorhus/atom-editorconfig/blob/master/grammars/editorconfig.json#L44):

```
(indent_style)\\s*(=)\\s*([Tt][Aa][Bb]|[Ss][Pp][Aa][Cc][Ee])\\b",
```

You can use a [scoped modifier](https://github.com/kkos/oniguruma/blob/master/doc/RE#L193) to flag a subexpression as case-insensitive.

So the live above could be shortened to this:

```json
"match": "(indent_style)\\s*(=)\\s*((?i)tab|space)\\b"
```

I'm assuming the `indent_style` part is case-sensitive, hence the character classes.

**Comment by yudai-nkt** [comment]
I didn't know about the `(?i)` modifier and the `:/downcase` feature, thanks @Alhadis!

And sorry for proposing a messy grammar.

**Comment by caleb531** [comment]
> I'm assuming the indent_style part is case-sensitive, hence the character classes.

@Alhadis This doesn't actually seem to be the case (pun intended). According to the [editorconfig homepage](http://editorconfig.org/), even properties are case-insensitive:

> Currently all properties and values are case-insensitive. They are lowercased when parsed.

I recommend modifying your PR (#117) to to account for this.

**Comment by florianb** [comment]
Thanks @Alhadis -- i wasn't aware of *that* detail, too. 🍪

**Comment by Alhadis** [comment]
Good catch. Updated.
