### ISSUE TITLE
Trimming trailing whitespace

### ISSUE THREAD

**Issue by scttcper** [sindresorhus/atom-editorconfig#118]
Whitespace is being removed one line per save. You can see eslint reacting to the saves. I'm on 1.7.0. The gif has a bunch of extra time at the end that I forgot to trim.
![saving](https://cloud.githubusercontent.com/assets/1400464/19737046/b960e548-9b66-11e6-8d33-a7f6bf0f72a6.gif)

```
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
insert_final_newline = false
trim_trailing_whitespace = false
```

My file looks like this, with a bunch of garbage whitespace.

``` javascript
module.exports = [
  { 
    name: 'BPM',  
    id: 'thebeat'  
  }, 
  {  
    name: 'Electric Area', 
    id: 'area33'
  },
];
```

**Comment by scttcper** [comment]
for some reason it isn't happening anymore after i've restarted my computer.

**Comment by scttcper** [comment]
With the whitespace package enabled its fine with only atom-editorconfig i'm still getting the issue.

**Comment by florianb** [comment]
Hey @scttcper - thank you for reporting that issue. Am i getting this right? You're saving the file and the no-trailing-spaces messages appear all at once (this is because eslint seems to lint on save) and then disappear line per line, in a frequency of 1 messages per second?

**Comment by florianb** [comment]
Hey @scttcper -- nothing more to do. I am able to reproduce that!

**Comment by florianb** [comment]
@scttcper -- the patch is flying. Please give me a hint if this embarrassing :bug: is 🔨 ed with the quadruple 🎶 of the tabbed 🎼 .

**Comment by scttcper** [comment]
Stay gold, 🦄

**Comment by florianb** [comment]
Yey... 👏 Thanks again @scttcper

**Comment by zauni** [comment]
Unfortunately in v2.0.2 I have the same problem... 

My editorconfig:
```ini
root = true

[*]
indent_style = space
indent_size = 4
charset = utf-8
end_of_line = LF
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false

[package.json]
indent_size = 2
```

I attached two screenshots, one before I hit save, and one after I hit save. Per save just one line gets trimmed. I have disabled the whitespace package from Atom.

Can you reproduce this? Would love to help :)

![editorconfig-screen1](https://cloud.githubusercontent.com/assets/663845/20000874/daf348b2-a279-11e6-8d55-5127ac5dc1c5.png)
![editorconfig-screen2](https://cloud.githubusercontent.com/assets/663845/20000873/daeefcd0-a279-11e6-8483-2bb9a9e49416.png)

**Comment by florianb** [comment]
@zauni -- thank you very much for reporting this! I am able to reproduce this.

**Comment by florianb** [comment]
Hey @zauni - i recently released a patch, i would appreciate if you could confirm that this solves the issue.

I am really sorry for any inconveniences and very thankful for your support! 🎁

**Comment by zauni** [comment]
Thank you very much @florianb 
That was really a speedy response and resolution 👍 Works like a charm now.
