### ISSUE TITLE
Can not hide wrap-guide

### ISSUE THREAD

**Issue by KarolAltamirano** [sindresorhus/atom-editorconfig#128]
After updating to v2.0.0 I am not able to hide wrap guide. Wrap guide is displayed even when wrap-guide package is disabled. When I disable also atom-editorconfig package the wrap guide disappears but I am not able to hide wrap guide when atom-editorconfig package is enabled.

**Comment by florianb** [comment]
@KarolAltamirano thanks for reporting that issue. Please provide your editorconfig-file and in which file-endings are affected.

**Comment by KarolAltamirano** [comment]
Hi @florianb, thank you for your quick reply.

My `.editorconfig` file looks like this:
```
root = true
[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false
```

I think the issue may be something with the new rule in version 2.0.0 `max_line_length`.

Attaching image:
[
<img width="782" alt="screen shot 2016-11-01 at 7 24 11 pm" src="https://cloud.githubusercontent.com/assets/8361660/19895167/287696d8-a069-11e6-9e09-3f6dee7e9cc6.png">
](url)

As you can see on the picture above there is a line (wrap guide) visible on the right but I have disabled wrap-guide package. So there is no way to hide this wrap guide. When I disable atom-editorconfig package the line is gone as expected. So probably it is something with this package. I am on mac os. Let me know if you can't reproduce and I can provide you more information.

**Comment by florianb** [comment]
@KarolAltamirano you are welcome -- thank you very much for your fast response! I am trying to reproduce your issue and we have likely a bug here.

Could you please add a screenshot of the output of the `EditorConfig: Show State`-command? I am especially interested in the value for `max_line_length`. Thanks in advance! 💝

**Comment by KarolAltamirano** [comment]
Adding the screenshot

<img width="452" alt="screen shot 2016-11-01 at 7 42 40 pm" src="https://cloud.githubusercontent.com/assets/8361660/19895759/68ebefa4-a06b-11e6-8c7f-0e4fcbee09ee.png">

**Comment by florianb** [comment]
@KarolAltamirano thanks a lot - i am investigating this issue.

**Comment by KarolAltamirano** [comment]
@florianb thank you very much. I need to go offline now but if there is anything else that would help you investigating the issue let me know I will answer you once I'm back.

**Comment by florianb** [comment]
@KarolAltamirano no worries - the patch 2.0.1 is pending and should resolve this issue. I would appreciate if you could check if this solves the issue for you. I am sorry for any inconveniences - thank you for your support! 🎁

**Comment by KarolAltamirano** [comment]
@florianb works great!!! Thank you for fixing it so quickly.
