### ISSUE TITLE
EditorConfig:fix-file doesnt fix anything

### ISSUE THREAD

**Issue by MiloBem** [sindresorhus/atom-editorconfig#135]
I have a source file that is generally properly formatted (manually) but I want to be able to do it automatically, so I removed some indentations and added trailing spaces to test it.

When I execute EditorConfig:fix-file command, either from the palette or a keybinding I get a message:

> The file app.module.ts conformed to the end_of_line and indent_style properties. No changes were applied.

It ignored these settings:
```
indent_size = 4
tab_width = 4
trim_trailing_whitespace = true
```

When I replaced some tabs with spaces and tried again I get this:

> Fixed EditorConfig-Properties	
> end_of_line	0
> indent_style	6
> Changes in total	6

so it replaces spaces with tabs and removes extra spaces, but the indentation is still not fixed

### Involved .editorconfig-files

```
root = true

[*]
charset = utf-8
indent_style = tab
indent_size = 4
tab_width = 4
trim_trailing_whitespace = true
end_of_line = lf
insert_final_newline = true

[*.md]
max_line_length = 0
trim_trailing_whitespace = false
```

### Directory structure

```
Please replace this by the output of `tree -a .` or `tree . \f`
whaat?
```

### Installed packages

```
Built-in Atom Packages (90)
├── about@1.5.3
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.52.0
├── atom-grammar-test@0.6.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.44.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.2
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.1
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.1
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.41.0
├── bracket-matcher@0.82.1
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.39.0
├── find-and-replace@0.201.0
├── fuzzy-finder@1.3.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.1
├── image-view@0.58.2
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── language-c@0.52.1
├── language-clojure@0.21.0
├── language-coffee-script@0.47.2
├── language-csharp@0.12.1
├── language-css@0.37.1
├── language-gfm@0.88.0
├── language-git@0.15.0
├── language-go@0.42.1
├── language-html@0.45.1
├── language-hyperlink@0.16.0
├── language-java@0.23.0
├── language-javascript@0.119.0
├── language-json@0.18.2
├── language-less@0.29.5
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.35.0
├── language-php@0.37.2
├── language-property-list@0.8.0
├── language-python@0.45.0
├── language-ruby@0.69.0
├── language-ruby-on-rails@0.25.0
├── language-sass@0.56.0
├── language-shellscript@0.22.4
├── language-source@0.9.0
├── language-sql@0.23.0
├── language-text@0.7.1
├── language-todo@0.28.0
├── language-toml@0.18.0
├── language-xml@0.34.9
├── language-yaml@0.26.0
├── line-ending-selector@0.5.0
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@0.53.1
├── notifications@0.65.0
├── one-dark-syntax@1.3.0
├── one-dark-ui@1.5.0
├── one-light-syntax@1.3.0
├── one-light-ui@1.5.0
├── open-on-github@1.2.0
├── package-generator@1.0.0
├── settings-view@0.242.2
├── snippets@1.0.2
├── solarized-dark-syntax@1.0.2
├── solarized-light-syntax@1.0.2
├── spell-check@0.67.1
├── status-bar@1.4.1
├── styleguide@0.47.0
├── symbols-view@0.113.0
├── tabs@0.100.2
├── timecop@0.33.2
├── tree-view@0.208.2
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.33.0
└── wrap-guide@0.38.1

Community Packages (4) /home/milo/.atom/packages
├── atom-beautify@0.29.13
├── atom-typescript@10.1.11
├── editorconfig@2.0.2
└── linter@1.11.18

└── (empty)
```

**Comment by florianb** [comment]
Hi @MiloBem -- thanks for getting in touch.

Currently the `Fix File`-command fixes **only** the indentation and end of line characters.

There are two reasons why it currently does not provide more functionality:

1. The EditorConfig-standard specifies that its implementation should only change the current behavior of the editor so that ongoing edits conform to the configuration.
2. Fixing preceding indentations relies on the used language grammar and the style you prefer for indentation.

We will probably never support the automated reformatting of source files for the 1st reason. But if we would like to fix the indentation-levels for you, we're not able for the 2nd reason. It is a bunch of work maintaining the EditorConfigs intentional functionality and i currently do not consider adding a beatification. There are already good alternatives for this task: https://atom.io/packages/atom-beautify

The intention of the `Fix File`-command is to help you fixing the invisibles after changing or adding the `.editorconfig`-file. This is somehow a drop-in replacement of the whitespace's convert between tabs and spaces function.

**Comment by MiloBem** [comment]
well, after reporting I realised that you probably dont want to deal with the grammar, but there is still the trailing whitespaces issue, that shouldn't have either problem.

**Comment by florianb** [comment]
There was a bug in the `trim_trailing_whitespace`-function which has been closed with 2.0.3. You might try that new version.

After reading your description i missed that you're facing an issue with trim_trailing_whitespace, i am sorry for that. Get back to me if this issue still exists.

**Comment by mliq** [comment]
@florianb I am on 2.0.3 and `trim_trailing_whitespace` stopped working for me. When I invoke `Show State` is shows everything as `auto`.

**Comment by florianb** [comment]
@mliq -- thanks for getting in touch. If the state of trim_trailing_whitespace shows `auto` - there were no appropriate editorconfig-files or settings found which may have been applied. Please open a new issue and provide all necessary information if you want help fixing this.
