### ISSUE TITLE
Set a default `.editorconfig`.

### ISSUE THREAD

**Issue by remcohaszing** [sindresorhus/atom-editorconfig#137]
I love the idea of editorconfig and this atom package. However, not every file or project uses it.

Since this package now shows a warning then the whitespace package is enabled, I'd really like to set a default .editorconfig for editing files system-wide more than ever.

I think it makes sense to use `$HOME/.editorconfig` for this purpose as a default, but it would be even better if it's configurable.

**Comment by florianb** [comment]
@remcohaszing -- thank you for getting in touch! 😄 

If there are no .editorconfig-settings applied to your current file, there should be no warning (yellow :mouse:). This would be a bug. In this case please provide the output of the `Show State`-command and the project-structure.

The topic of "global" editorconfig-files was already discussed in #14 -- please take a look there.

**Comment by remcohaszing** [comment]
I was sure the `.editorconfig` from my home dir wasn't applied... but I can't seem to reproduce it. Sorry for the inconvenience!

**Comment by florianb** [comment]
@remcohaszing -- you are welcome. Do not hesitate to come back if you have any questions.
