### ISSUE TITLE
Create a global .editorconfig

### ISSUE THREAD

**Issue by freiguy1** [sindresorhus/atom-editorconfig#14]
All of my projects have the same indenting scheme per file.  Including a .editorconfig in each with the same information seems a bit redundant.  I'd prefer to put one config at ~/.atom/.editorconfig which defines the global settings for all projects.  These settings could be overridden on a per-directory basis.

Does this sound possible?

**Comment by gauthier-delacroix** [comment]
Sorry for updating this old issue but I'm working on different projects, stored on different sources (local, company network, ...). That means that I have no common root for all my projects to put the .editorsettings into, and I can't put a `.editorsettings` link in every project I make a small contribution to.

A system global file, used when no root `.editorconfig` file is found in the project tree, would be great IMHO...

**Comment by florianb** [comment]
I wasn't aware anybody was commenting on this issue. However - i think providing a global editorconfig is a dangerous thing to do. Especially if you're contributing to lot of different projects, because doing so would enforce your local settings, which may malform the current project.

The current behavior is that editorconfig leaves the control to Atom if there is no editorconfig. Which means that Atom will use the defaults (likely) from the language-grammar. If this is not intended a editorconfig should be contributed to the target project, to carefully respect the prevailing settings.

**Comment by robert-zaremba** [comment]
>  However - i think providing a global editorconfig is a dangerous thing to do. Especially if you're contributing to lot of different projects, because doing so would enforce your local settings, which may malform the current project.

But the default .editorconfig  would be used only when there is no project (local) .editorconfig file

**Comment by florianb** [comment]
That's the point. This works well as long nobody is contributing with a different default setting.

BTW: EditorConfig already supports global configurations by leaving out `root = true` and putting an `.editorconfig` into your root folder.

This question is also being discussed in the editorconfig-repo already. I would like to close this issue in favor of https://github.com/editorconfig/editorconfig/issues/245.

Anyways -- any change to the way how editorconfig-files are traversed, found and used belong to the editorconfig-standard (and should be filed in https://github.com/editorconfig/editorconfig). This package uses [editorconfig-core-js](https://github.com/editorconfig/editorconfig-core-js) which is responsible for a standard compliant implementation.

Thanks everybody!

**Comment by dietergeerts** [comment]
What if you share such thing through an npm module? We do this for all common configs, so it would be nice if there's a way to point to that shared file. I tried a hard link, but git just commits the file, so others don't have it as a hard link, symlinks don't work well with git, so I would like to see some kind of extend feature.

**Comment by dietergeerts** [comment]
I found another way: I just copy the file in a postinstall step and have it in my .gitignore file.

**Comment by florianb** [comment]
Hi @dietergeerts - thanks for getting in touch (and sharing your solution). I personally would also prefer having f.e. `~/.editorconfig` in the chain of search paths. Unfortunately i don't think the standard will implement that in the future.
