### ISSUE TITLE
Improving implementation of `max_line_length`

### ISSUE THREAD

**Issue by florianb** [sindresorhus/atom-editorconfig#143]
It turned out that even the EditorConfig-specification requires `max_line_length` being applied by inserting (hard) wraps, a raising user base treats that as unexpected if they explicitly disabled "Soft Wraps" in Atom.

How should the implementation of `max_line_length` being improved to fit the user expectations better?

1. The overall Atom-configuration of "Soft Wraps" should be respected.
2. The gutter should be shown
  2.1 Therefore the default wrap-guide should still be hidden

and

❓ The EditorConfigs-wrap-guide should turn red if any line exceeds the `max_line_length`

**Comment by florianb** [comment]
I proposed a change of the official `max_line_length`-property -- support would be appreciated: https://github.com/editorconfig/editorconfig/issues/280

**Comment by mik01aj** [comment]
I'm not sure if this is related, but I noticed that enabling `max_line_length = 80` in my (global) `.editorconfig` causes the `wrap-guide` to disappear. And removing this line causes the guide to appear again. Looks like a bug to me.

**Comment by florianb** [comment]
Hi @mik01aj, thank you for reporting this. It might be that the wrap-guide implementation is faulty due to the current transition of Atom towards 1.13. To take care about your issue i'd like to ask you to open a new issue containing all necessary information. Thanks in advance! 👍

**Comment by mik01aj** [comment]
Ok, see #163.

**Comment by rjmunro** [comment]
IMHO max_line_length should position the wrap-guide, and possibly highlight any characters that are past it, e.g. with a red background. As Atom doesn't have a built in text wrap command, it can't do much else, unless it implemented wrap functionality itself, or worked in cooperation with another plugin.

Soft wrapping is almost the exact opposite of what it should do. It makes it look like the file complies with the preferred width when it doesn't.

**Comment by manuelbieh** [comment]
softwrap, in my opinion, makes absolutely no sense here. The editorconfig spec says hardwrap - hardwrapping is not possible so using softwrap instead is just "for the user's eyes". Setting the wrap-guide to max_line_length should be fine to indicate that the code should wrap just there.

The user's softwrap setting(s) should be taken into consideration here. If the user has softwrap enabled, atom-editorconfig should softwrap at max_line_length. If it's disabled the wrap-guide should be moved to max_line_length (as it was a few weeks ago iirc).

**Comment by vosi** [comment]
its so annoying that i can disable softwrap, that i had to disable editorconfig plugin

**Comment by florianb** [comment]
The `max_line_length` will respect at least the `SoftWrap` setting in the next minor-release.
