### ISSUE TITLE
Deprecated selector in `editorconfig/styles/atom-editorconfig.less`

### ISSUE THREAD

**Issue by rumpelsepp** [sindresorhus/atom-editorconfig#144]
In `editorconfig/styles/atom-editorconfig.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .ecfg-wrap-guide` => `atom-text-editor.editor .ecfg-wrap-guide`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by florianb** [comment]
Thanks @rumpelsepp -- i expected this to happen but couldn't find the resource. I will add this the next time i'm touching the source. 😄 💝

**Comment by rumpelsepp** [comment]
I just used the atom build in report issue button. It generated this text automatically :D

**Comment by florianb** [comment]
😆 Manchmal sieht man vor lauter Bäumen den Wald nicht.. 🎄

**Comment by rumpelsepp** [comment]
so schauts aus. :)

**Comment by florianb** [comment]
Fixed with #146
