### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by zenopopovici** [sindresorhus/atom-editorconfig#149]
Could we have a proper CHANGELOG? It's really annoying to hunt down the changes.

**Comment by florianb** [comment]
Could you elaborate on what you expect?

**Comment by sindresorhus** [comment]
A summary of changes in a release here: https://github.com/sindresorhus/atom-editorconfig/releases/new

**Comment by zenopopovici** [comment]
Hey,

I can't access that URL. I think it only works for you.
A standard CHANGELOG with each version and short description of what was changed would be nice. Or at least GitHub standard release notes for each version.

Zeno.

**Comment by florianb** [comment]
Currently i only foster a major/minor-changelog in the readme. I will think about adding dedicated patch-release notes but it's unlikely that i will have the time foster this by hand. I will think about changing the commit messages and introduce an automated changelog but it will take its time.

Until this will happen i suggest you reading https://github.com/sindresorhus/atom-editorconfig/commits/master - the patches should usually be connected to issues.

**Comment by zenopopovici** [comment]
Thanks! Anyway really cool work.
