### ISSUE TITLE
Package seems not applying on all open files after startup

### ISSUE THREAD

**Issue by florianb** [sindresorhus/atom-editorconfig#154]
After starting Atom in a project where already some files have been opened (Atom restores the open editors), the editorconfig is not being applied until you're switching the pane/reenter the current editor.

:bulb: Initialization should use `workspace.getTextEditors()`

**Comment by schrej** [comment]
What's the status on this? It's somewhat annoying 😅

**Comment by florianb** [comment]
This issue should be fixed -- feel free to come back if you're facing any troubles with it!
