### ISSUE TITLE
Adding extra indentation in Apex code

### ISSUE THREAD

**Issue by fricco** [sindresorhus/atom-editorconfig#156]
Hello, I'm using Atom-Beautify in a Windows 7 64 bit machine and haven't change anything in the configuration. I'm working with Apex code (.cls and .trigger) and for some reason when I Beatify the file, it's adding additional tabs. For example:
@isTest
private class MyTestClass {
(tab)(tab)@testSetup
(tab)(tab)static void createCommonData(){
(tab)(tab)(tab)(tab)Account a = newAccount();
(tab)(tab)(tab)(tab)insert a;

When what I'm expecting is:
@isTest
private class MyTestClass {
(tab)@testSetup
(tab)static void createCommonData(){
(tab)(tab)Account a = newAccount();
(tab)(tab)insert a;

**Comment by florianb** [comment]
Hi @fricco -- thanks for getting in touch, your issue belongs to the beautify-package, take a look at #138 to get more information.

💝
