### ISSUE TITLE
end_of_line not working

### ISSUE THREAD

**Issue by ChristianSchramm** [sindresorhus/atom-editorconfig#158]
Hey there,

since the last updates ig got some problem with line-endings.

.editorconfig is set to  line-ending lf, but it doesn't work for atom.

# http://editorconfig.org
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

Active state is end_of_line = \n. But i got mixed or crlf instead of lf.

Notification:

Tab Type: You editor's configuration setting "Tab Type" (currently "soft" prevents the editorconfig-property indent_style from working.
"Tab Type" must be set to "auto" to fix this issue.

whitespace: It is likely that the whitespace-package prevents the following properties from working reliably: insert_final_newline, trim_trailing_whitespace.
You may deactivate or disable the whitespace-package to fix that issue.

Active Configuration
Editorconfig-Property	Applied Setting
end_of_line	\n
charset	utf8
indent_style	space
indent_size/ tab_width	2
insert_final_newline	true
trim_trailing_whitespace	true
max_line_length	auto
(auto: atom-editorconfig is not influencing that behavior. A full description of the properties can be found on editorconfig.org.)

**Comment by florianb** [comment]
hi @ChristianSchramm - thanks for reporting that issue. I need more information to be able to help you:

- When do you get mixed eols (after pressing enter, after pasting stuff)?
- How do you find out you have mixed eols?
- Which packages do you have installed (`apm list`)?

Thanks in advance! 💝

**Comment by ChristianSchramm** [comment]
Hey,

- when i use enter after i get mixed eols
- i have a plugin that shows me which line-ending my files actually have
- and here the list :)

I hope it helps to find a solution. Thanks

Built-in Atom Packages (89)
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.52.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.45.0
├── base16-tomorrow-dark-theme@1.3.0
├── base16-tomorrow-light-theme@1.3.0
├── one-dark-ui@1.6.2
├── one-light-ui@1.6.2
├── one-dark-syntax@1.5.0
├── one-light-syntax@1.5.0
├── solarized-dark-syntax@1.0.5
├── solarized-light-syntax@1.0.5
├── about@1.7.0
├── archive-view@0.62.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.13.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.4
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.1
├── bookmarks@0.42.0
├── bracket-matcher@0.82.2
├── command-palette@0.39.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.40.0
├── find-and-replace@0.202.2
├── fuzzy-finder@1.4.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.2
├── image-view@0.60.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── line-ending-selector@0.5.0
├── link@0.31.2
├── markdown-preview@0.158.8
├── metrics@1.1.2
├── notifications@0.65.1
├── open-on-github@1.2.1
├── package-generator@1.0.1
├── settings-view@0.243.1
├── snippets@1.0.4
├── spell-check@0.68.4
├── status-bar@1.4.1
├── styleguide@0.47.2
├── symbols-view@0.113.1
├── tabs@0.103.0
├── timecop@0.33.2
├── tree-view@0.210.0
├── update-package-dependencies@0.10.0
├── welcome@0.35.1
├── whitespace@0.35.0
├── wrap-guide@0.38.2
├── language-c@0.54.0
├── language-clojure@0.22.1
├── language-coffee-script@0.48.0
├── language-csharp@0.13.0
├── language-css@0.40.1
├── language-gfm@0.88.0
├── language-git@0.15.0
├── language-go@0.43.0
├── language-html@0.46.1
├── language-hyperlink@0.16.1
├── language-java@0.24.0
├── language-javascript@0.122.0
├── language-json@0.18.3
├── language-less@0.29.6
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.37.3
├── language-property-list@0.8.0
├── language-python@0.45.1
├── language-ruby@0.70.2
├── language-ruby-on-rails@0.25.1
├── language-sass@0.57.0
├── language-shellscript@0.23.0
├── language-source@0.9.0
├── language-sql@0.25.0
├── language-text@0.7.1
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.34.12
└── language-yaml@0.27.1

Community Packages (37) C:\Users\Christian Schramm\.atom\packages
├── atom-beautify@0.29.13
├── atom-jade@0.3.0
├── atom-monokai@0.10.4
├── auto-indent@0.5.0
├── blame@0.10.0
├── color-picker@2.2.3
├── compare-files@0.8.0
├── compass@0.9.1
├── editorconfig@2.0.5
├── emmet@2.4.3
├── git-history@3.2.0
├── git-plus@5.25.3
├── git-time-machine@1.5.4
├── jade-autocompile@0.8.3
├── jade-snippets@0.5.0
├── keybinding-cheatsheet@0.1.1
├── language-jade@0.7.2
├── linter@1.11.18
├── linter-jscs@4.1.0
├── linter-jshint@3.0.1
├── linter-jsonlint@1.3.0
├── linter-scss-lint@3.0.4
├── merge-conflicts@1.4.4
├── minimap@4.25.6
├── minimap-git-diff@4.3.1
├── monokai@0.18.0
├── pigments@0.37.0
├── project-manager@3.3.3
├── project-quick-open@0.5.0
├── seti-icons@1.3.4
├── seti-syntax@1.0.1
├── seti-ui@1.3.2
├── sort-lines@0.14.0
├── tabs-to-spaces@1.0.2
├── terminal-panel@1.14.1
├── todo-show@1.8.0
└── trailing-spaces@0.3.2

└── (empty)

**Comment by florianb** [comment]
Thanks @ChristianSchramm -- i am not sure if i got you right.

You get wrong line endings after pressing enter when your file already contains mixed line endings?

Did you try to invoke `EditorConfig: Fix File` beforehand?

**Comment by ChristianSchramm** [comment]
Hey there,

found the solution. I'm using Windows and maybe some update changed my global config. So this ticket can be closed.

Sorry for that, but thanks for your fast response.

**Comment by florianb** [comment]
Great news! Happy coding! ☕️
