### ISSUE TITLE
Two deprecated selectors

### ISSUE THREAD

**Issue by JonSn0w** [sindresorhus/atom-editorconfig#160]
#### Use the ```atom-text-editor``` tag instead of the ```editor``` class.  
In styles\atom-editorconfig.less: Use the `atom-text-editor` tag instead of the `editor` class.
_________

#### Style elements within text editors using the ```atom-text-editor::shadow``` selector or the ```.atom-text-editor.less``` file extension.If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.  
In styles\atom-editorconfig.less: Style elements within text editors using the ```atom-text-editor::shadow``` selector or the ```.atom-text-editor.less``` file extension.
If you want to target overlay elements, target them directly or as descendants of ```atom-overlay``` elements.

**Comment by florianb** [comment]
Thank you @JonSn0w & @leonardosouza, you're getting the deprecation-warning since you're using the upcoming beta-release of Atom 1.13.

A release solving this is pending - i will come back to you as soon as it is published.

**Comment by FabianMeul** [comment]
I'm alsing having this issue in Atom 1.12.7 (Non-beta)

**Comment by florianb** [comment]
Thanks for reporting this @FabianMeul - a patch is already published and should be automatically enrolled when Atom 1.13 is getting released. I beg for patience and i am sorry for the inconveniences.

**Comment by FabianMeul** [comment]
No problem @florianb . Thanks for the follow-up 👍

**Comment by florianb** [comment]
@FabianMeul, @JonSn0w: i hope this issue is now fixed. I will close it for now. Feel free to come back if you faced any troubles! Thank you for your collaboration @JonSn0w!

💝
