### ISSUE TITLE
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

### ISSUE THREAD

**Issue by leonardosouza** [sindresorhus/atom-editorconfig#161]
In styles/atom-editorconfig.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by florianb** [comment]
Thanks for reporting, this is a dupe of #160
