### ISSUE TITLE
Setting max_line_length causes atom wrap-guide to disappear

### ISSUE THREAD

**Issue by mik01aj** [sindresorhus/atom-editorconfig#163]
I noticed that enabling `max_line_length` in my (global) `.editorconfig` causes the [`wrap-guide`](https://github.com/atom/wrap-guide) to disappear. And removing this line causes the guide to appear again. Looks like a bug to me.

.editorconfig file:

```
[*]
max_line_length = 80
```

Disabling and re-enabling the `wrap-guide` package helps, but only for the currently open editor pane.

Related comment by @florianb from #143:

> It might be that the wrap-guide implementation is faulty due to the current transition of Atom towards 1.13.

**Comment by florianb** [comment]
@mik01aj -- thanks a lot! I assume you're using Atom 1.12.x?

**Comment by rjmunro** [comment]
I find that setting max_line_length always causes soft-wrap to that width, even though I do not have "soft wrap at preferred line length" enabled.

**Comment by florianb** [comment]
@rjmunro - that's the current implementation according to the standard. See #142 and #133.

**Comment by cliffordfajardo** [comment]
Just wanted to show a visual of what's happening. Immediately after adding `max_line_length` and saving, the wrap guide line to go away. (Atom 1.12.7)

![editorconfig](https://cloud.githubusercontent.com/assets/6743796/21063910/eaeab79c-be0c-11e6-8dc7-cc1f5a331c89.gif)

**Comment by florianb** [comment]
@cliffordfajardo, @rjmunro, @mik01aj: i refactored the wrap-guide implementation. I hope this issue is now fixed. I would appreciate if anybody could prove this. Thanks or your patience! ☕️

**Comment by cliffordfajardo** [comment]
@florianb - I'm not experiencing the problem anymore 🎉😀. Thanks!
