### ISSUE TITLE
Is this a replacement for the whitespace package?

### ISSUE THREAD

**Issue by mhulse** [sindresorhus/atom-editorconfig#186]
Editor config addon let's me know there are potential conflicts with White Space package.

How many of you disable white space package in place of this addon?

I usually have an `.editorconfig` for all my projects, but sometimes not.

~~Out of curiosity, to the other users, How do you manage editorconfig plugin and whitespace package/atom indentation settings?~~

What is the recomendation for Atom users? Should we disable whitespace package? Just curious what the best approach is?

**Comment by florianb** [comment]
@mhulse - that's a pretty good question. Currently we're not replacing 100% of the whitespace package's functionality (namely most of the exposed commands, f.e. to turn leading spaces into tabs and vice versa).

atom-editorconfig should respect Atom's default configuration if there is no editorconfig property found (or editorconfig file at all). Using the "Fix File"-command allows you to reformat leading (and trailing) spaces, too - but this would need an editorconfig file.

I personally use it as a complete replacement for the whitespace package. But i have to admit that i most of the times have a editorconfig-file.

I guess we have a blind spot for people not using editorconfig files and then need to do a lot of transformations of leading spaces.

I hope that answers your question.

**Comment by mhulse** [comment]
Very helpful! Thank you so much @florianb, I greatly appreciate the help. :)

I have not used the "fix file" command, that's cool! Looking forward to using it.

I think I will just go for a full-on replacement and try to have `.editorconfig` in all projects.

Thanks again for your help!

I ❤️  editorconfig!

**Comment by florianb** [comment]
@mhulse i am happy to hear that! Enjoy using Atom-Editorconfig and feel free to come back if you face any issues or have any other feedback! 😄  🎁
