### ISSUE TITLE
How to use it !

### ISSUE THREAD

**Issue by Praveenv98** [sindresorhus/atom-editorconfig#195]
Hi
My mentoring organisation uses editorconfig. I didn't use it so far in my projects. As a beginner how I should use editorconfig in atom. I found docs not helping me. Please provide me guidelines for using editorconfig.
Thank you...

**Comment by alaycock** [comment]
The [editorconfig website](http://editorconfig.org/) should provide all the documentation you need to write your first .editorconfig file. To use the plugin you just need to install it, and the .editorconfig file should do the rest of the work.

**Comment by Praveenv98** [comment]
And one more doubt..
If I write a .editorconfig file and then I begin to code in my normal style. After completing .editorconfig will do the indentation work for me ?

**Comment by alaycock** [comment]
This plugin changes your editor settings so any new code you write will match your settings (spaces vs tabs, etc). If you want to fix old code, check out something like [atom-beautify](https://atom.io/packages/atom-beautify).

If you don't indent your code, this plugin won't do anything. You still have to worry about indentation yourself.

**Comment by Praveenv98** [comment]
Thank you @alaycock !
