### ISSUE TITLE
Rules are not being applied for a particular situation (See the comment for more details)

### ISSUE THREAD

**Issue by KSXGitHub** [sindresorhus/atom-editorconfig#196]
#### Type 1

1. In Atom, _open some files_ that are ruled by editorconfig (e.g. `indent_size`). In order to make issue appear obvious, rules in `.editorconfig` should contradict with atom's own editor settings (e.g.  `indent_size = 2` vs Atom's `Tab size = 4`)
2. _Reload_ Atom (leave editor tabs open). i.e. `Window: Reload` in Command Palette or <kbd>Ctrl-Shift-F5</kbd>
3. _Select tab_ of file that is ruled by editorconfig

#### Type 2

1. In Atom, _open some files_ that are ruled by editorconfig (e.g. `indent_size`). In order to make issue appear obvious, rules in `.editorconfig` should contradict with atom's own editor settings (e.g.  `indent_size = 2` vs Atom's `Tab size = 4`)
2. _Restart_ Atom (leave editor tabs open). i.e. Close Atom window then re-launch it
3. _Select tab_ of file that is ruled by editorconfig

### Expected behaviour

After step 2 of each type, editorconfig still has effect these editor tabs (e.g. <kbd>tab</kbd> makes 2 spaces)

### Actual behaviour

After step 2, editorconfig has no effects on opened tabs, only Atom's own editor settings applies (e.g. <kbd>tab</kbd> makes 4 spaces)

### Workaround

Closed opened tabs, re-open their files

**Comment by florianb** [comment]
Hi @KSXGitHub - thanks for your investigation. Your issue (at least "Type 1") is related to #176.

I would like to change this behavior, but i haven't had the time to dig into it.

**Comment by p-boiko** [comment]
Another temp workaround: disable and enable the package

**Comment by sindresorhus** [comment]
Closing as Atom is abandoned.
