### ISSUE TITLE
Fix Shortcut Key

### ISSUE THREAD

**Issue by EmpireWorld** [sindresorhus/atom-editorconfig#197]
Hi.

Thanks for the awesome job, but it needs a shortcut key to run Fix command.

Thanks.

**Comment by florianb** [comment]
Hi @EmpireWorld - thank you very much for getting in touch. I do currently not consider adding a global shortcut for any Editorconfig functions, since there seems no significant amount of interest for that feature.

Feel free to add a shortcut for your needs by adding f.e.

    	'ctrl-alt-f':     'EditorConfig:fix-file'

to your `keymap.cson`.

**Comment by EmpireWorld** [comment]
Nice. thanks. i will do it. good alternative.
