### ISSUE TITLE
tabType broken on settings change with no .editorconfig

### ISSUE THREAD

**Issue by guandalf** [sindresorhus/atom-editorconfig#202]
When editorconfig package is installed and no .editroconfig file is not present (I haven't tested with a .editorconfig file), changing any settings in the language-yaml builtin package, turns the tabType setting from soft to hard, resulting in hard tabs inserted in file while editing.

Forcing file type to something different from YAML and back to Autodetect, fixes the wrong tab behavior.

### Involved .editorconfig-files

```
None
```

### Directory structure

```
N/A
```

### Installed packages

```
Community Packages (17) /Users/stefano.guandalini/.atom/packages
├── Hydrogen@1.20.0
├── atom-material-syntax@1.0.6
├── atom-material-ui@2.0.4
├── atom-python-test@0.7.0
├── atom-python-virtualenv@0.14.0
├── autocomplete-python@1.10.2
├── autocomplete-robot-framework@3.3.0
├── busy-signal@1.4.3
├── editorconfig@2.2.2 (disabled)
├── intentions@1.1.5
├── language-docker@1.1.8
├── language-robot-framework@2.2.0
├── language-vue@0.23.1
├── linter@2.2.0
├── linter-ansible-linting@1.3.0
├── linter-python@3.1.2
└── linter-ui-default@1.6.7```

**Comment by florianb** [comment]
Hi @guandalf - thanks for reporting this! Please give me some time to address that, i personally won't find time to work on this until next week. Thank you in advance.. ☕️

**Comment by sindresorhus** [comment]
Closing as Atom is abandoned.
