### ISSUE TITLE
atom-editorconfig is broken

### ISSUE THREAD

**Issue by florianb** [sindresorhus/atom-editorconfig#204]
Atom-EditorConfig seems to be broken due to substantial changes to Atom's API.

A full rewrite to 3.0.0 is pending.

**Comment by heruan** [comment]
Indeed it does not work on Atom Beta with `atom-ide` packages. Is this related?

**Comment by florianb** [comment]
@heruan - probably. I am currently working on a rewrite. I'll try to prioritize my work on this.

**Comment by rm-code** [comment]
It seems to work for me on Atom `1.22.1`.

**Comment by florianb** [comment]
Thanks for the feedback @rm-code - unfortunately some functions may not work as expected. But i am still working on the rewrite.

**Comment by noirbizarre** [comment]
Hi :wave: !

The package is still broken on Atom 1.23.3, any progress on the rewrite ?

**Comment by florianb** [comment]
Hi - yes there is progress.
________________________________
Von: Axel Haustant <notifications@github.com>
Gesendet: Montag, 22. Januar 2018 13:58
An: sindresorhus/atom-editorconfig
Cc: Florian Breisch; Author
Betreff: Re: [sindresorhus/atom-editorconfig] atom-editorconfig is broken (#204)


Hi 👋 !

The package is still broken on Atom 1.23.3, any progress on the rewrite ?

**Comment by noirbizarre** [comment]
Thanks for the response ! :+1:

**Comment by florianb** [comment]
@varemenos, yes it is - the referenced version number was wrong.

**Comment by the-j0k3r** [comment]
So... No point reporting bugs then, since this re-write is happening right?

**Comment by sindresorhus** [comment]
Closing as Atom is abandoned.
