### ISSUE TITLE
Rewrite to Stuart Little (3.0.0)

### ISSUE THREAD

**Issue by florianb** [sindresorhus/atom-editorconfig#205]
- [ ] Recheck Atom's API-changes (Notifications, Buffer/Editor-Settings)
- [ ] Consider use of AVA
- [ ] Recheck all issues
- [ ] Rewrite test-suite
- [ ] Add code coverage

Support is very welcome. 🍻

**Comment by vtambourine** [comment]
Stuart Little?

**Comment by florianb** [comment]
I began to name the milestones of major releases after mice.

**Comment by rm-code** [comment]
I'm confused ... I mean we are on `2.2.2` already?

**Comment by florianb** [comment]
Right - fixed, thanks

**Comment by florianb** [comment]
I decided to drop maintenance. Sorry.

See https://github.com/sindresorhus/atom-editorconfig/issues/231
