### ISSUE TITLE
Case sensitive; editorconfig spec says it should not be?

### ISSUE THREAD

**Issue by mhulse** [sindresorhus/atom-editorconfig#209]
Atom 1.23.1
Atom EditorConfig 2.2.2

### Involved .editorconfig-files

```
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = false
indent_size = 4
indent_style = tab

[vagrantfile]
indent_size = 2
indent_style = space
```

### Directory structure

```
.editorconfig
Vagrantfile
```

Noticing that `vagrantfile` does not match the file name of `Vagrantfile`, though, the [docs](http://editorconfig.org/) say:

> Currently all properties and values are case-insensitive. They are lowercased when parsed.

Thanks!

**Comment by florianb** [comment]
The cited sentence applies for properties and their values, not sections. You're welcome.

**Comment by mhulse** [comment]
Ahhh, you are right! Sorry that I did not catch that myself.

In fact, there's no reference to the case sensitivity of sections. I'll follow up with EditorConfig repo/folks.

Thanks again!

**Comment by florianb** [comment]
You're welcome - i wasn't aware this could be an issue. Happy holidays! 🎄
