### ISSUE TITLE
Highlight fails on ‘unset’ keyword

### ISSUE THREAD

**Issue by valtlai** [sindresorhus/atom-editorconfig#218]
I have .editorconfig like this:

```ini
root = true

[*]
indent_style = tab
indent_size = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = false

[*.php]
insert_final_newline = unset

[*.yml]
indent_style = space
indent_size = 2
```

The PHP section is highlighted like this:

![The whole “insert_final_newline = unset” line is not highlighted.](https://user-images.githubusercontent.com/5496284/38778321-efc085d4-40c0-11e8-9ce1-1b718ed73352.png)

If I change `unset` to `false`, it’s highlighted correctly:

![](https://user-images.githubusercontent.com/5496284/38778322-f167bcd6-40c0-11e8-83eb-7e9069e4ccf3.png)

If I give any property a value of `unset`, the whole line gets unhighlighted.

**Comment by florianb** [comment]
Hi @valtlai - thanks for reporting this. It will take me some time to look for this (looks like an issue with the regexes in the grammar).

You might fasten the process up if you're take a look yourself and file a PR. ☕️

**Comment by Alhadis** [comment]
Rewritten grammar completely to be more permissive and structured.

Don't worry, I've done this before. Like, uh, [~20 times](https://atom.io/users/alhadis/packages).
