### ISSUE TITLE
Update Readme? Is this plugin working with latest version of Atom?

### ISSUE THREAD

**Issue by WadeShuler** [sindresorhus/atom-editorconfig#223]
I skimmed through the issues and I saw a few things where you said you are working on a re-write and that the feature wasn't working after a certain Atom version.

**So what is the current state of this plugin?**
Is it still mostly working with say, Atom v1.28.2? Should we not use this plugin until you get it re-written? - If this is the case, please update the README file plainly at the beginning, so all of us know not to use it.

**If it mostly works, what features don't work?**

**Do we need to disable the built in `whitespace` plugin?** If we are supposed to disable it, it isn't really clear in the README. It has been mentioned, but didn't really stress that I had to...

---

PS: I am here and asking, because I am going through all of my plugins and cleaning house. Checking for outdated/broken/dead plugins, ones I don't need, etc.

PPS: Sorry, but your GitHub issue template doesn't really apply.

**Comment by Alhadis** [comment]
I'm now maintaining it. =) On the verge of cutting a new release, so if you uninstalled it, be ready to re-install. 👍
