### ISSUE TITLE
Button to toggle auto-format on/off

### ISSUE THREAD

**Issue by trusktr** [sindresorhus/atom-editorconfig#228]
Sometimes (f.e. when `trim_trailing_whitespace` is turned on), I don't want the editor to modify the file on save. Most of the time I do, but sometimes I don't.

It'd be nice if editorconfig had a button like the `prettier` package does, to toggle auto-format on save on/off.

Here's what the prettier button looks like in the bottom status bar:

![screen shot 2018-10-24 at 1 19 22 pm](https://user-images.githubusercontent.com/297678/47458836-718a8a00-d78f-11e8-82ce-b49d58bf55bf.png)

It'd be super awesome to have this with EditorConfig too

It'd be nice to do like Prettier by having the option in the plugin settings to both enable/disable the button and enable/disable auto-format.

This way, we can avoid changing the git-tracked `.editorconfig` inside of a project, and we get easier control of behavior.

**Comment by Alhadis** [comment]
IMHO, that's stepping outside the responsibilities of this package. EditorConfig isn't an auto-formatter in the sense that Prettier is; it's simply enforcing basic formatting settings at the behest of the project's author.

I can add a command for saving a file without normalisation, but I don't want to make it too easy for users to skip normalisation willy-nilly. There's a reason files are configured to trim whitespace, or trim trailing newlines, or what-have-you… 😉

**Comment by sindresorhus** [comment]
Closing as Atom is abandoned.
