### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by qwelias** [sindresorhus/atom-editorconfig#230]
There's a lot of issues related to recent Atom versions, and it doesn't seems like anyone cares to fix them.
Should the package be marked as obsolete?

Not to blame anyone, just to make it clear.

**Comment by florianb** [comment]
Thanks @qwelias - I've been pushing that step too long. I will officially drop the maintenance for the package but i offer to stay here as a "maintainer" helping anybody who wants to pick it up.

I'm going to write a separate text the current state of the package.
