### ISSUE TITLE
Multi-page

### ISSUE THREAD

**Issue by hcbiz** [sindresorhus/atom-editorconfig#234]
Thank you very much for contributing! :heart: Leave us any feedback, idea or issue -- we are trying hard to improve atom-editorconfig!

### Involved .editorconfig-files

```
The current .editorconfig file does not permit opening of multiple pages in the atom editor. Pages are opened in different files and detatched fron one another. Please update the code to avoid this
```

### Directory structure

```
Please replace this by the output of `tree -a .` or `tree . \f`
```

### Installed packages

```
Please replace this by the output of `apm list`
```

**Comment by Alhadis** [comment]
I'm sorry, what do you mean by "multiple pages"? Can you elaborate?

Also, please tell me what version of `editorconfig` and Atom you're using.

**Comment by hcbiz** [comment]
Each time you open a new document, a separate UI detatched from the
previous one is created rather than opening it side by side

**Comment by Alhadis** [comment]
I'm still confused. Please take some screenshots (preferably before and after the incident occurs).

**Comment by Alhadis** [comment]
@hcbiz, if you're unsure how to take a screenshot, [this site can help you](https://www.take-a-screenshot.org/).

**Comment by Alhadis** [comment]
No response from submitter; closing.
