### ISSUE TITLE
Unrecognized declaration name `max_line_length`

### ISSUE THREAD

**Issue by AlexWayfer** [sindresorhus/atom-editorconfig#244]
![image](https://user-images.githubusercontent.com/6510020/83507621-779b2d80-a4d1-11ea-8adf-fbe62c6903b7.png)

![image](https://user-images.githubusercontent.com/6510020/83507467-44589e80-a4d1-11ea-98cc-fd6b6e843a5c.png)

### Involved .editorconfig-files

```
root = true

[*]
indent_style = tab
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
max_line_length = 120

[*.yml]
indent_style = space
```

### Directory structure

Doesn't matter.

### Installed packages

```
editorconfig@2.6.0
```

**Comment by Alhadis** [comment]
Good catch. Seems like #236 overlooked EditorConfig settings that [aren't mandatory](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#supported-by-a-limited-number-of-editors) (or in their words, _"supported by a limited number of editors"_, of which Atom is one of them).

Will fix.

**Comment by Alhadis** [comment]
Sorry about the wait. I had to investigate why the `linter` specs weren't running (which required a little research). This should be fixed in the next release. :)

**Comment by AlexWayfer** [comment]
> Sorry about the wait.

No problem, thank you very much!
