### ISSUE TITLE
Too Many Filetypes?

### ISSUE THREAD

**Issue by bobrocke** [sindresorhus/atom-editorconfig#25]
My .editorconfig file has:
```
# 2 space indentation
[*.{yaml,yml,cson,md,ini,conf,xml}]
indent_style = space
indent_size = 2
```
Atom picks up the .conf preference to use Spaces: 2, but it doesn't pick up the .xml.

**Comment by sindresorhus** [comment]
What happens if you place the `xml` first? Is it picked up then?

**Comment by bobrocke** [comment]
Yes.

**Comment by sindresorhus** [comment]
Can't reproduce the issue. Make sure you're using the latest version of Atom and try reinstalling the plugin.
