### ISSUE TITLE
Wrong EditorConfig highlighting for inline comment

### ISSUE THREAD

**Issue by Youssef1313** [sindresorhus/atom-editorconfig#253]
### Involved .editorconfig-files

```editorconfig
abc = abc#abc
```

The `#` and everything after is highlighted as a comment. This doesn't adhere to [latest EditorConfig specification](https://spec.editorconfig.org/#no-inline-comments).

**Comment by Alhadis** [comment]
I wasn't aware the spec was updated. Thanks for the heads up. 👍
