### ISSUE TITLE
Links in Preferences->Packages Go To Xcode

### ISSUE THREAD

**Issue by bobrocke** [sindresorhus/atom-editorconfig#26]
When I click in a link within the displayed info for a package in Preferences..., Xcode launches instead of my web browser!

v0.165.0

See also:https://discuss.atom.io/t/links-in-preferences-packages-go-to-xcode/14050

**Comment by sindresorhus** [comment]
https://discuss.atom.io/t/links-in-preferences-packages-go-to-xcode/14050/8
