### ISSUE TITLE
Generates git:// URLs instead of https://

### ISSUE THREAD

**Issue by silvenon** [sindresorhus/atom-editorconfig#27]
I think this is common to all your Atom packages. For some reason the generated link to the repo has the `git://` protocol instead of `https://`. I couldn't figure out why, but the `package.json` in the Atom package differs from the `package.json` in the repo.

![screenshot 2015-01-15 14 01 19](https://cloud.githubusercontent.com/assets/471278/5757857/d5b55b36-9cbf-11e4-8ccd-9c78b35f2068.png)

**Comment by sindresorhus** [comment]
You already opened a ticket on Atom: https://github.com/atom/atom/issues/4776
