### ISSUE TITLE
`trim_trailing_whitespace` property

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/atom-editorconfig#3]
http://editorconfig.org

> trim_trailing_whitespace: set to true to remove any whitespace characters preceding newline characters and false to ensure it doesn't.

The bundled [whitespace](https://github.com/atom/whitespace) plugin has an option for this called `removeTrailingWhitespace`

I can change it with: `atom.config.set('whitespace.removeTrailingWhitespace', true);`, but that changes it globally and we definitely don't want that. From what I can figure out from the docs it isn't possible to override config on a per buffer basis like you can with Sublime.

**Comment by SamVerschueren** [comment]
I

**Comment by florianb** [comment]
As already mentioned, this functionality is implemented by the [atom-whitespace](https://github.com/atom/whitespace)-package.

As soon as i have found out how to interact nicely with the whitespace-package, we're going on to implement that functionality.

I'll try to find a solution with the package-maintainer. ☕
