### ISSUE TITLE
Tab size and atom-beautify

### ISSUE THREAD

**Issue by jerone** [sindresorhus/atom-editorconfig#32]
When I set the `indent_style` to `tab` and set the `tab_width` to `4`, the tab size is correctly set (4 chars width), but the same number of tabs is also added. I don't know if this is an editorconfig issue or something is interfering with [atom-beautify](https://github.com/Glavin001/atom-beautify). I'm hoping someone can confirm this before taking further action.

**Steps to reproduce:**

1. Create file `test.less` with content (see no indention):

        element {
        color: red;
        }

2. Add following `.editorconfig`:

        [**.less]
        indent_style = tab
        tab_width = 4

3. Now right-click editor and choose "Beautify editor contents".
4. **Result** (see 4 tabs indention):

        element {
        				color: red;
        }

p.s. `tab_size` isn't mentioned in the readme, but well used in `index.js`.

**Comment by kevva** [comment]
You should use `indent_size`.

**Comment by jerone** [comment]
[**@kevva**](https://github.com/kevva) commented on [6 mei 2015 17:41 CEST](https://github.com/sindresorhus/atom-editorconfig/issues/32#issuecomment-99517191 "2015-05-06T15:41:02Z - Replied by Github Comment Enhancer"):
> You should use `indent_size`.

According to [the source](https://github.com/sindresorhus/atom-editorconfig/blob/master/index.js#L24-L31) `tab_size` is used to setTabLength...

**Comment by sindresorhus** [comment]
This is an issue with `atom-beautify`: https://github.com/Glavin001/atom-beautify/issues/339

**Comment by piotr-cz** [comment]
`tab_width` seems to work now

**Comment by duard** [comment]
When I call CTRL+ALT+B in Atom (Ubuntu) it ident my ruby.rb file with tab_width 4
Default install
no changes

**Comment by florianb** [comment]
@duard please open a new issue with all information necessary to reproduce or understand your findings.
