### ISSUE TITLE
Not picking up configuration

### ISSUE THREAD

**Issue by bobrocke** [sindresorhus/atom-editorconfig#34]
My `.editorconfig` file is:

```
# top-most EditorConfig file
root = true

# Default
[*]
charset = utf-8
end_of_line = lf
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = tab
indent_size = 3

# 2 space indentation
[*.{xml,yaml,yml,cson,md,ini,conf}]
indent_style = space
indent_size = 2
```

But PHP files are using Spaces:3 instead of Tabs:3:

![www grav dev - atom](https://cloud.githubusercontent.com/assets/2962426/7761152/36727db2-fff0-11e4-8178-61e40e8e0b5f.jpg)

Do I have something configured wrong?

**Comment by ezekg** [comment]
My config file has been having issues being picked up as well. Does editorconfig require the default whitespace plugin to be enabled?

**Comment by ismay** [comment]
Mine too. When saving a `.js` file in version 0.208.0, editorconfig does not trim trailing whitespace with the following config:

```
# EditorConfig helps developers define and maintain consistent
# coding styles between different editors and IDEs
# editorconfig.org

root = true

[*]
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = space
indent_size = 2

[*.js]
indent_style = space
indent_size = 2

[*.hbs]
indent_style = space
indent_size = 2

[*.css]
indent_style = space
indent_size = 2

[*.html]
indent_style = space
indent_size = 2

[*.{diff,md}]
trim_trailing_whitespace = false

```

When I add the line `trim_trailing_whitespace = true` to the `.js` block, it *does* trim the trailing whitespace. So it doesn't seem to be picking up the global configuration.

**Comment by lucasmotta** [comment]
+1

**Comment by brandonb927** [comment]
Ok I thought I was going crazy when on load It looks like Atom 1.0 is going to use my `.editorconfig`, however after about 2 seconds it reverts back to the Atom settings config and not using my projects `.editorconfig`.

+1 on this issue

**Comment by bobrocke** [comment]
@brandonb927 This has proven to be a difficult mess. And I know the Atom folks have struggles with the "right" solution in the case of the file content, .editorconfig, and Atom's preferences differing. I don't think I've worked out how the conflict is handled within Atom.

If you hand edit your file to make it conform to your .editorconfig settings, will Atom respect that on load even if Atom's preferences are different?

**Comment by brandonb927** [comment]
I'm not sure what you mean by "hand edit"? Do you mean that I should just edit the `cson` file manually to have it reflect my editorconfig settings?

**Comment by bobrocke** [comment]
Yes.

**Comment by brandonb927** [comment]
That... is not ideal :} I have an editorconfig in many projects I work on daily, switching between them frequently too. You're saying I should manually edit the Atom config whenever I switch then?

**Comment by bobrocke** [comment]
No. I'm saying that Atom does not seem to handle .editorconfig, it's preferences, and what it finds in a file well if they don't all match up. I was suggesting a way to fix that for one file - make that file match .editorconfig and see if that "sticks."

**Comment by brandonb927** [comment]
Ah, simple misunderstanding. I'll try that and see if it works.

**Comment by bobrocke** [comment]
@lee-dohn has written up a bunch on the topic.

**Comment by nfantone** [comment]
+1 on this. 

I have absolutely *no* idea on how this package works, but it sure does not apply my `.editorconfig` settings. What am I supposed to do? Autoindent? How does this indent my source files, exactly? Is there any kind of magic keyboard shortcut?

**Comment by gitgrimbo** [comment]
Hi,

I deleted the following two lines from `C:\Users\xxx\.atom\config.cson` and when I restarted Atom my `.editorconfig` settings seemed match the formatting when I beautify (Ctrl+Alt+B), but not when I edit (auto-indentation isn't correct, for example).

````
    softTabs: false
    tabLength: 4
````

**Comment by c4milo** [comment]
I'm having the same problem.

**Comment by brandonb927** [comment]
Atom seems to be picking up on my config now

**Comment by brandonb927** [comment]
Hmm I realized that Atom also stopped picking up my config a few releases ago :(

**Comment by bux578** [comment]
Same here.

**Comment by marcelombc** [comment]
+1

**Comment by carsy** [comment]
:+1:

**Comment by nfantone** [comment]
Maybe it wasn't such a good idea to close the issue?

**Comment by EloB** [comment]
+1

**Comment by jbatte47** [comment]
+1, not working for me

**Comment by jaimeschettini** [comment]
+1

**Comment by sikhote** [comment]
+1

**Comment by matias91** [comment]
+1

**Comment by garretmh** [comment]
+1

**Comment by verlok** [comment]
+1

**Comment by rochapablo** [comment]
+1

**Comment by florianb** [comment]
@rochapablo: I would really appreciate if you could open a "new" issue with details about your problems.

For anyone else landing here: The atom-editorconfig-plugin is in a **stable** and mostly tested state and should work as intended.

The editor might behave unexpected if third-party plugins or languages conflict with the editorconfig-settings and/or the file is already malformed according to the editorconfig-rules.

ℹ️ Please open a **new** issue in that case - we're happy to help.

P.s.: please do **not** post to this issue. Since the plugin has evolved a bit in the past weeks it is absolutely unlikely that your issue belongs in any way to the reasons why this was opened in the first place.

**Comment by noahehall** [comment]
this doesnt work

**Comment by florianb** [comment]
@noahehall: Please read my comment above - if you're facing any issues please open a **new** issue and consider especially:

> The editor might behave unexpected if third-party plugins or languages conflict with the editorconfig-settings and/or the file is already malformed according to the editorconfig-rules.

**Comment by kaifaust** [comment]
Removing the "whitespace" plugin from config.cson and restarting atom solved this for me.

**Comment by hiddentao** [comment]
@kaifaust That worked for me too, thanks.

**Comment by verlok** [comment]
👍🏼
