### ISSUE TITLE
Switch to `event-kit` instead of `emissary`

### ISSUE THREAD

**Issue by kevva** [sindresorhus/atom-editorconfig#39]
From https://github.com/atom/emissary:

> Achtung! This library is currently used in Atom and various Atom dependencies, but our long-term plan is to transition away from it in favor of the simpler [event-kit](https://github.com/atom/event-kit) library. Don't depend on supporting this library forever.

**Comment by sindresorhus** [comment]
Lol, I just commented on that. :+1:

**Comment by sindresorhus** [comment]
Not needed: https://github.com/sindresorhus/atom-editorconfig/commit/c0f83009c252e05be6cbd205060a7c68b755b630
