### ISSUE TITLE
`insert_final_newline` property

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/atom-editorconfig#4]
http://editorconfig.org

> insert_final_newline: set to true ensure file ends with a newline when saving and false to ensure it doesn't.

See #3

**Comment by JaKXz** [comment]
It appears that this setting isn't taking effect for me on Atom 0.169.0 with v0.2.3 running on OSX 10.10.1.

**Comment by sindresorhus** [comment]
@JaKXz Of course it isn't. It's not implemented yet. Hence this issue...

**Comment by JaKXz** [comment]
Oh. That's odd, I could swear I'd seen it working before... but obviously I was just seeing things.

**Comment by jerone** [comment]
@JaKXz commented on [10 jan. 2015 06:31 CET](https://github.com/sindresorhus/atom-editorconfig/issues/4#issuecomment-69443465 "2015-01-10T05:31:35Z - Replied by Github Comment Enhancer"):
> Oh. That's odd, I could swear I'd seen it working before [and I had disabled Atom's whitespace plugin]... but obviously I was just seeing things. Sorry for the noise.

[atom-beautify](https://atom.io/packages/atom-beautify) supports this:

> Js end with newline

**Comment by bucaran** [comment]
@sindresorhus What's the problem with implementing this feature? Is it Atom related?

**Comment by anthonyryan1** [comment]
Subscribing. Interested in this for `insert_final_newline = false` on hand-optimized SVG files (saving as many bytes as possible).

**Comment by EloB** [comment]
This core module `whitespace` is adding a new line to my files even if I tell `insert_final_newline = false` in `.editorconfig `
![image](https://cloud.githubusercontent.com/assets/476567/11143616/c0374466-89f6-11e5-9bfa-e690b690fa8e.png)

**Comment by sindresorhus** [comment]
@EloB Please read the thread before commenting... https://github.com/sindresorhus/atom-editorconfig/issues/4#issuecomment-69443309

**Comment by EloB** [comment]
@sindresorhus WTF? I can't see anything about that is actually `whitespace` core module that is the real issue here. This would probably help the guy who is going to fix this.

**Comment by florianb** [comment]
Okay, this functionality is implemented by the [atom-whitespace](https://github.com/atom/whitespace)-package. Since this is a core-package its functionality has to be treated as first-class-citizen of Atom.

The good message about this is, we're able to easily add support for `insert_final_newline`, by modifying the text-buffer on the `onWillSave`-event.

The bad message is, the whitespace-package may override a "negative" setting, since it may be called after our hook.

I'll try to find a solution with the package-maintainer.

**Comment by mahnunchik** [comment]
Any news?

**Comment by florianb** [comment]
Our feature-request is not supported. It is suggested to work around the issue, which is what we will do. I assume to get this issue into WIP in the next days.

I am sorry for the inconvenience - i was some weeks away from desk and i am still getting back. :)
