### ISSUE TITLE
Add a CHANGELOG.md

### ISSUE THREAD

**Issue by coliff** [sindresorhus/atom-editorconfig#40]
Would be interesting to see what's changed with each update of this package. I think if you add a CHANGELOG.md to the directory it'll be viewable from the Settings of this package from within Atom.

**Comment by sindresorhus** [comment]
That would just be a copy paste of the commit log. Open an Atom issue about showing the commit log between versions of there's no changelog.

**Comment by underyx** [comment]
http://keepachangelog.com/

Relevant sections are
 - What makes unicorns cry?
 - Why can’t people just use a `git log` diff?
