### ISSUE TITLE
Improve generate command

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/atom-editorconfig#46]
This plugin now has a command to generate an `.editorconfig` file based on the current settings.

Here's some things that could be improved with:
- [ ] If indentation is not 2-space and a package.json is found in root, add this rule: 

```
[package.json]
indent_style = space
indent_size = 2
```

With `indent_style` only being needed if the existing style is tab indented.
- [ ] Infer settings like `indent_style`, `indent_size` from `.jshintrc`, `.eslintrc`, `.jscsrc`, etc. 
## 

Anything else?

**Comment by cemrich** [comment]
JSHint deprecated the [`indent`](http://jshint.com/docs/options/#indent) property so parsing the `.jshintrc` may be not necessary.

**Comment by florianb** [comment]
I would prefer adding wisely chosen file-format-based minimum-settings like `trim_trailing_whitespace` for *.md/markdown or `indent_style` space (& tab-length 2) for json and yaml-files. Those settings should be combined based on the file-endings found in the entire project.

If we would aim reading stack-specific configuration files this would become a neverending story which is pretty difficult to maintain. Adding file-specific defaults will just end up in a single json-file which contains all necessary rules.

**Comment by AlexWayfer** [comment]
I've found necessary thing: https://github.com/editorconfig/editorconfig-defaults

I think plugins just can use the official JSON.

**Comment by sindresorhus** [comment]
Closing as Atom is abandoned.
