### ISSUE TITLE
Show the "Settings" Button

### ISSUE THREAD

**Issue by gsklee** [sindresorhus/atom-editorconfig#49]
Settings are available for this plugin, so please make the "Settings" button show up accordingly:

![http://i.imgur.com/5lemSVm.png](http://i.imgur.com/5lemSVm.png)

![http://i.imgur.com/lY2ofF9.png](http://i.imgur.com/lY2ofF9.png)

**Comment by sindresorhus** [comment]
Sounds similar to https://github.com/atom/settings-view/issues/345, but I thought that was fixed. Not up to me though. Open an issue there.
