### ISSUE TITLE
Generate .editorconfig from current settings

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/atom-editorconfig#5]
Would be useful with a command that would create a new .editorconfig based on the users current settings.

**Comment by slang800** [comment]
I got this working in https://github.com/slang800/editorconfig-tools - it's not specific to atom (it infers settings based on the files in the project, rather than the config.cson of the user), but it does do what you described.

**Comment by varemenos** [comment]
I'm trying to prepare a PR for this issue. So far I've gathered all the info required and stored the new .editorconfig file's content in a variable. I'm currently researching on how to save and where to save the generated .editorconfig file.

https://github.com/sindresorhus/atom-editorconfig/compare/master...varemenos:master
