### ISSUE TITLE
windows: opening file causes file to be marked as edited. 

### ISSUE THREAD

**Issue by Kilowhisky** [sindresorhus/atom-editorconfig#52]
When i open a project on a windows machine and then click on a file with editorconfig enabled the file is marked as edited in need of saving (aka  blue dot) even though i have not edited the file. 

Here's my .editorconfig. 

```
# EditorConfig helps developers define and maintain consistent
# coding styles between different editors and IDEs
# editorconfig.org

root = true


[*]
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = space
indent_size = 4

[*.js]
indent_style = space
indent_size = 4

[*.hbs]
insert_final_newline = false
indent_style = space
indent_size = 4

[*.css]
indent_style = space
indent_size = 4

[*.html]
indent_style = space
indent_size = 4

[*.{diff,md}]
trim_trailing_whitespace = false
```

and my atom config.

```
"*":
  "exception-reporting":
    userId: ""
  welcome:
    showOnStartup: false
  core:
    disabledPackages: [
      "editorconfig"
    ]
  editor:
    invisibles: {}
    scrollPastEnd: true
    showIndentGuide: true
    fontSize: 17
  "linter-jshint": {}
  "linter-less": {}
  docblockr: {}
  "spell-check": {}
  jsformat: {}
  "atom-beautify":
    _analyticsUserId: ""
  pigments: {}
  linter: {}
".ini.source":
  editor:
    scrollPastEnd: true
    showIndentGuide: true
```

**Comment by andrewstart** [comment]
I've had this happening too. I've noticed that when I change the file's line ending settings with the line-ending-selector plugin from LF to CRLF that the changes in the file go away, even though the .editorconfig settings specify LF line endings.

**Comment by sindresorhus** [comment]
You've set `end_of_line = lf` in your .editorconfig file, but you're on Windows, so git probably checked the files out as CRLF, hence EditorConfig will convert it to LF as you've requested in the .editorconfig file. Working as intended.
