### ISSUE TITLE
Enabling editorconfig plugin scrambles my files

### ISSUE THREAD

**Issue by pkese** [sindresorhus/atom-editorconfig#54]
After upgrade to atom 1.1, I got all my files in editor somehow scrambled and realigned.
When analyzing the issue, I have figured out that this happens only when I enable the `editorconfig` package (if the package is disabled, it doesn't happen).

Here is a screenshot of my file with `editorconfig` disabled:
![atom-pre](https://cloud.githubusercontent.com/assets/278492/11060381/1d40b10a-87a0-11e5-8f45-eea24efc9f26.png)

And again with `editorconfig` package enabled:
![atom-post](https://cloud.githubusercontent.com/assets/278492/11060390/3525c382-87a0-11e5-911c-2bd9e9b98ad5.png)

My `.editorconfig` file is:

		# EditorConfig is awesome: http://EditorConfig.org

		# top-most EditorConfig file
		root = true

		# Unix-style newlines with a newline ending every file
		[*]
		end_of_line = lf
		insert_final_newline = true
		indent_style = tab
		indent_size = 4
		charset = utf-8

		# 4 space indentation
		[*.{py}]
		indent_style = space
		indent_size = 4

		# 2 space indentation
		[*.{js,jsx}]
		indent_size = 2
		indent_style= space

		# Indentation override for all JS under lib directory
		#[lib/**.js]
		#indent_style = space
		#indent_size = 2

		# Matches the exact files either package.json or .travis.yml
		#[{package.json,.travis.yml}]
		#indent_style = space
		#indent_size = 2

**Comment by sindresorhus** [comment]
I don't really see how Editorconfig could be doing this. Looks more like a bug in Atom caused by this plugin changing some settings, or might that we go through and change the line endings https://github.com/sindresorhus/atom-editorconfig/blob/b4c59d8eeeb48faa568a16fdae2cffc1cdf5bae4/index.js#L48.

**Comment by pkese** [comment]
@sindresorhus thanks for the direction about where to search for problems...

So now I'm debugging what is going on... If I comment out the line `replace(preferredLineEnding);` in the place that you have pointed me to at `index.js`, the error disappears (of course then line-ending replacement doesn't work any more, but at least my files aren't scrambled any more).

I have also checked my config and have found out that in that specific function that you have pointed out, `config.end_of_line` is set to `'lf'`, `preferredLineEnding` is `\n` and my source files are encoded using `\r\n`

I'll keep you posted about my findings.

**Comment by pkese** [comment]
...and if I convert my source files to UNIX style line endings (with just `\n` instead of `\r\n`) my files don't get scrambled either.

I'm wondering if this make things repeatable (can you possibly try and open a Windows encoded file and see if you get the same result yourself?)

**Comment by pkese** [comment]
same thing happens if my file is encoded with unix `\n` and `preferredLineEndings` is `\r\n`. So as soon as the replaced line endings is not the same length, things get scrambled.
When length is the same, things work fine.

It leads me to assume that ther is a bug in Atom's buffer's `backwardsScanInRange`.

**Comment by dwelle** [comment]
Having same problem. If the file is in `CRLF` and the editorconfig is set to `LF`, the file becomes a mess.

**Comment by andreialecu** [comment]
Seeing the same problem here on windows. I can reproduce it by opening most files in ionic, one that it is particularly bad on is:

https://github.com/driftyco/ionic/blob/master/js/angular/service/scrollDelegate.js

Screenshot:
![image](https://cloud.githubusercontent.com/assets/697707/11685100/41acfbfc-9e7f-11e5-858c-6140d7a9ae7d.png)

**Comment by pkese** [comment]
Luckily, there's a fix for this now in atom's text-buffer:
https://github.com/atom/text-buffer/pull/120
