### ISSUE TITLE
Slow at opening lagre files

### ISSUE THREAD

**Issue by hultberg** [sindresorhus/atom-editorconfig#56]
Hello

After installing editorconfig I noticed that when opening a CSS file with over 3500 lines it takes about 3-4 secs before the I can start edit the file and before language highlight highlights the file. During the 3-4 secs Atom completely freezes.

When there is no editorconfig in my project this issue do not occur even with editorconfig enabled.

Occurs in Atom 1.2.4 and Atom 1.3.0-beta6 with only editorconfig enabled.

Here is my editorconfig:
````
# top-most EditorConfig file
root = true

# All files configuration
[*]
end_of_line = lf
insert_final_newline = true
charset = utf-8
trim_trailing_whitespace = true

# PHP Configuration
[*.php]
indent_style = space
indent_size = 4

# JS configuration
[*.js]
indent_style = space
indent_size = 2

# CSS configuration
[*.css]
indent_style = space
indent_size = 2

# SCSS configuration
[*.scss]
indent_style = space
indent_size = 2
````

**Comment by pkese** [comment]
Oh... so that is what had been slowing down my Atom.
It would be nice to have a flag to not fiddle with existing line endings.

+1

**Comment by hultberg** [comment]
Cc: @sindresorhus

**Comment by sindresorhus** [comment]
Yeah, it should be changed to only run the replacement if the line ending differ. PR welcome.
