### ISSUE TITLE
Support for more encoding-types?

### ISSUE THREAD

**Issue by aripalo** [sindresorhus/atom-editorconfig#57]
Currently the [README.md](https://github.com/sindresorhus/atom-editorconfig/blob/master/readme.md) says only `latin1`, `utf-8`, `utf-16be` and `utf-16le` are supported. 

It seems that Atom does support other encodings: https://github.com/atom/atom/issues/1806
(and looking at `encoding-selector` package there's quite many from diffent `ISO-8859-` variants to `Windows 1252` https://github.com/atom/encoding-selector/blob/master/lib/main.coffee)

Just wondering why? Just not implemented or is the README just outdated?

Well, okay `utf-8` is pretty much default these days, but sometimes you just have to work with legacy stuff that is something else.

**Comment by sindresorhus** [comment]
Those are the ones supported by EditorConfig:

> charset: set to latin1, utf-8, utf-8-bom, utf-16be or utf-16le to control the character set. Use of utf-8-bom is discouraged.
> \- http://editorconfig.org
