### ISSUE TITLE
Crashes on load on Atom 1.4.0-beta0. The crash makes atom core unusable.

### ISSUE THREAD

**Issue by francoiscote** [sindresorhus/atom-editorconfig#58]
Trying to open Atom 1.4.0-beta0 with this package results in a white screen with the dev-tools opened:

**Reproduction Steps:**
- Deactivate all packages except editorconfig
- open atom-beta.

**Screenshots and GIFs**
![screen shot 2015-12-10 at 1 50 21 pm](https://cloud.githubusercontent.com/assets/116375/11724967/1dfae874-9f45-11e5-9f81-d0cc1d2b6f42.png)

**Additional information:**

* Problem can be reproduced in safe mode: No
* Problem started happening recently, didn't happen in an older version of Atom: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by Arcanemagus** [comment]
I'm not seeing this on v1.4.0-beta3 (and didn't see it on v1.4.0-beta0). Are you still seeing this, and if so do you see it with a blank Atom profile? (Backup/move `~/.atom`, launch Atom to recreate it, install editorconfig _only_)

**Comment by francoiscote** [comment]
I'm unable to reproduce. with a blank profile under v1.4.0-beta3 and v1.4.0-beta0
Also tried reactivating the plugin in my regular atom profile and it works ok (in both beta3-beta0). I don't understand since I consistently got this bug before.

Thanks for taking the time, and sorry about wasting your time on this. I wanted to help.

**Comment by Arcanemagus** [comment]
Bug reports are always helpful, even if they turn out to not be an issue :wink:.
