### ISSUE TITLE
Switching views makes Atom default settings clobber editorconfig-applied settings

### ISSUE THREAD

**Issue by myrrlyn** [sindresorhus/atom-editorconfig#59]
Problem OS: Windows, Mac, and Linux

Description: Opening a file that is subject to `editorconfig` files results in the `editorconfig` rules being properly applied. Switching to another editor view (another file in the project, opening the Settings page) and returning to that file results in Atom's default settings being applied over `editorconfig`'s.

Example: Atom defaults to 4-wide auto tabs. Use `editorconfig` to set certain files as 2-wide hard tabs. Open one of these files: tabs are displayed 2 spaces wide. Open another file, even one subject to the same rules. Switch back to the first editor window. Tabs are now displayed as 4 spaces wide.

Furthermore, if Atom defaults to either 'hard' or 'soft' tabs, this setting overrules `indent_style` in the `.editorconfig` file, even on freshly-opened files that have had `indent_size` properly applied to hard tabs.

Summary: Needs more assertiveness.

**Comment by florianb** [comment]
This bug is issue seems to be part of a more complex malfunction. I move its solution into a separate issue #81 and therefore close this issue. I'd appreciate if follow that issue, too.

Thanks for your patience. ☕
