### ISSUE TITLE
trim_trailing_whitespace ignored when using Vim mode's `:w`

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/atom-editorconfig#60]
When using ViM mode in Atom and a file's `trim_trailing_whitespace` setting is `true`, a `Cmd+S` will trim the trailing whitespace but `:w` will not.

**Comment by sindresorhus** [comment]
That option isn't implemented here yet https://github.com/sindresorhus/atom-editorconfig/issues/3.

**Comment by Qix-** [comment]
Is it Atom doing the trimming then?

**Comment by sindresorhus** [comment]
Dunno. Does it still happen when you disable this plugin?

**Comment by Qix-** [comment]
Sure does.

**Comment by sindresorhus** [comment]
Hmm, weird. Maybe one of these transformations indirectly affects something else. Can you try to disable them all and enable one after another to narrow down which of them is the one causing it?

https://github.com/sindresorhus/atom-editorconfig/blob/b4c59d8eeeb48faa568a16fdae2cffc1cdf5bae4/index.js#L30-L56

**Comment by Qix-** [comment]
That linked code doesn't have anything that would strip trailing whitespace from what I can tell. I think it might just be an editor configuration. It's probably honestly a bug in the Vim bindings.
