### ISSUE TITLE
With multiple buffers open, current buffer contents are replaced with another's

### ISSUE THREAD

**Issue by caleb531** [sindresorhus/atom-editorconfig#62]
**What happens?**
If there are multiple documents open, the contents of the current buffer (*i.e. the selected document) is replaced by the contents of some other open buffer. This has rendered Atom difficult to use in some cases.

**When does this happen?**
- When restarting the editor via the *Reload* command or simply by quitting and launching Atom again
- For any project managed by EditorConfig (*i.e. some parent directory contains an `.editorconfig`)
- Only when there are multiple buffers open

**How can I reproduce?**

1. Open an EditorConfig project and open several files
2. Reload the editor via the Command Palette (or `ctrl-option-cmd-l` on OS X)

**Can you be sure this is an EditorConfig issue?**

With certainty. The issue only disappears when I disable the editorconfig package, and the issue only started happening today when editorconfig v1.2.3 was released.

Thanks so much for all of your work on this project, @sindresorhus. I really enjoy the convenience provides by editorconfig, and I would really hate to disable it because of this pesky bug.

Thanks,
Caleb

**Comment by sindresorhus** [comment]
I think I know what's going on. Can you try v1.2.4?

**Comment by sindresorhus** [comment]
// @dbachko

**Comment by caleb531** [comment]
Excellent! The fix works—all is right with the world again. Thanks very much for the quick fix, @sindresorhus!
