### ISSUE TITLE
Dont Refresh All Files

### ISSUE THREAD

**Issue by dev-sandman** [sindresorhus/atom-editorconfig#63]
There is not a mechanism to automatically set any settings at all a project file, it is necessary to open a file, save it and close it.

**Comment by sindresorhus** [comment]
No idea what you're asking. Can you try to be more clear? :)

**Comment by dev-sandman** [comment]
I cloned a project that has a .editorconfig file and used the atom-editorconfig plugin, but to apply the settings throughout the project I need to open all the files and then they modify the following configuration (eg end_of_line = lf) hence I can save the change. There is no way to change all the files at once without this procedure!

**Comment by sindresorhus** [comment]
That's outside the scope of this plugin.
