### ISSUE TITLE
Does this even work?

### ISSUE THREAD

**Issue by corysimmons** [sindresorhus/atom-editorconfig#64]
- I have .editorconfig in root of project.
- I have Atom Editorconfig plugin.

```
# All recursive files starting from this file's dir
root = true
[*]

# Tab indentation style
indent_style = tab
tab_width = 2

# Standardize whitespace
trim_trailing_whitespace = true
end_of_line = lf
insert_final_newline = true
```

![image](https://cloud.githubusercontent.com/assets/224636/12821210/6be4ad2e-cb30-11e5-94ec-ebf1bf6f3146.png)

But it doesn't automatically change my editor config to use tabs on this project.

I have Atom Tab Type setting set to `auto`.

Any help would be appreciated.

**Comment by mdmoreau** [comment]
Having a similar issue on Ubuntu 14.04.  Also noticing that the command palette doesn't show anything at all for editorconfig.

**Comment by mdmoreau** [comment]
Seems like this ended up fixing itself for me somehow.  Not sure what happened, but after a few restarts of Atom things are working properly.

**Comment by decademoon** [comment]
I'm also having this issue.

**Comment by zenwalker** [comment]
+1

**Comment by zenopopovici** [comment]
Can't get it to work ...

**Comment by carloschneider** [comment]
+1

**Comment by zenwalker** [comment]
I found the old ussue with same problem #34

**Comment by afkatja** [comment]
Even after a restart of Atom, .editorconfig settings are not applied.

**Comment by unluisco** [comment]
+1

**Comment by mellowchanter** [comment]
If the CSS of the indentation is 'space' when I paste , does not change 'tab'.
Maybe this is same problem.

```
root = true

[*]
end_of_line = lf
charset = utf-8
indent_style = tab
indent_size = 4
trim_trailing_whitespace = true
```

**Comment by mreschke** [comment]
Same here, not applying my settings at all.  Even deleted any tag reference manually in config.cson, restarted and it still won't apply the .editorconfig settings.  I am using nuclide.

**Comment by retlehs** [comment]
seeing the same issues — this package doesn't work for me. it would be awesome if atom had native support for editorconfig:

https://github.com/atom/atom/issues/6589
https://discuss.atom.io/t/editorconfig-support/327

**Comment by andreynering** [comment]
It also doesn't work for me. Installing it has no effect. Atom just use its own settings.

**Comment by iamso** [comment]
I thought it was working, until I added different settings for PHP files, but it doesn't seem to pick them up. 
I have already cleared the storage and reinstalled the package.

Here are the settings:
```
root = true

[*]
indent_style = space
indent_size = 2
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false

[*.php]
indent_style = tabs
indent_size = 4
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

Works in Sublime though;

**Comment by claviska** [comment]
+1

**Comment by florianb** [comment]
Thanks everybody here for participation. This seems to be a complex topic with a wide spread influence - i beg for patience until we did some further investigations on the issue. :candy:

**Comment by fronteed** [comment]
@florianb looks like this package still doesn't work as expected. Bump a new version, please.

**Comment by florianb** [comment]
@fronteed we are still facing issues with the final proper setup of the TextEditor instance. Unfortunately the changes we do to configure the TextEditor get immediately overridden by the Atom-environment.

This issue has currently my full attention.

As soon as it is solved i'll initiate the 1.2.5-release. Thank you very much for your patience and care!

🍰 ☕

**Comment by florianb** [comment]
This bug is issue seems to be part of a more complex malfunction. I move its solution into a separate issue #81 and therefore close this issue. I'd appreciate if follow that issue, too.

Thanks for your patience. ☕

**Comment by cliffordfajardo** [comment]
Simply wanted to share my experience with this:  My editorconfig didn't take effect until I restarted Atom editor.

From the command palette you can type `reload` to trigger `Window: Reload` or you can just quit & restart your editor.
