### ISSUE TITLE
Improve Package Loading Time

### ISSUE THREAD

**Issue by tillkruss** [sindresorhus/atom-editorconfig#68]
Could you improve the loading time?

![screen shot 2016-03-12 at 12 25 00 pm](https://cloud.githubusercontent.com/assets/665029/13725125/9c6c2550-e84d-11e5-833c-3e752fdcd93b.png)

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/atom-editorconfig/issues/66.
