### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/atom-editorconfig#71]
I don't have the time to maintain this project anymore. There's a lot of users, so would be nice if someone stepped up as an active maintainer.

**Comment by slang800** [comment]
:hand: - I'll do it. I've got a few other packages for atom and I use editorconfig regularly.

**Comment by sindresorhus** [comment]
@slang800 Thanks for stepping up! You're now a collaborator on this repo :)

-

The guidelines are simple. Be kind to everyone. Larger changes should come in a pull request. Smaller ones can be committed directly. Follow the existing [code style](https://github.com/sindresorhus/xo) (Tip: `$ xo --fix` can fix many issues) and ensure `npm test` passes before pushing a commit. You can use branches in this repo, but clean them up afterwards. I like a clean commit history, so when merging a pull request, either ask the contributor to [squash](http://stackoverflow.com/questions/11396069/squash-to-only-one-proper-commit-for-github-pull-request) their commits or do it for them manually.

-

Still open to adding more people if anyone else is interested.

**Comment by sindresorhus** [comment]
The next step would be to triage the open issues. Next would be to implement more EditorConfig properties. There's no Atom API's for those, so will probably need to be implemented by manually modifying the text content.

**Comment by florianb** [comment]
Although i wasn't very present here in matters of code-pledges yet i want to help to make atom-editorconfig better. I leave the decision to you if you'd like to see me also helping out maintaining the plugin.

**Comment by sindresorhus** [comment]
Any help is welcome, especially non-code help, like triaging issues, improving docs, writing tests, etc.

@florianb You're now a collaborator :)

**Comment by florianb** [comment]
Thanks -- i'm happy to help! :beers:

**Comment by simison** [comment]
Perhaps this could be moved to @editorconfig org?

**Comment by eddiemonge** [comment]
@sindresorhus Ill take a shot at helping

**Comment by sindresorhus** [comment]
@eddiemonge Added :)

**Comment by gorriecoe** [comment]
Could this be maintained by Atom Core?  Considering that Github has native support for editorconfig wouldn't it also make sense for them to do the same on their editor.

**Comment by florianb** [comment]
Thanks for that suggestion @gorriecoe. This question with even on more specific aspects of the editoroconfig-functionality is already answered months ago: no.

The reason (that part answering your question) behind this decision is at first that the Atom-team decided to provide a more sophisticated per language configuration within Atom (while the editorconfig is based on file-endings).

The core team will not spent any time to contradict their decision. Another reason is - this package is working and it is maintained. Why taking it over?

I will close this issue. If anybody wants to support atom-editorconfig, please do it. You are welcome.
