### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/atom-editorconfig#72]
Should have tests to ensure it's working and we don't introduce regressions.

#### Resources

- https://github.com/sindresorhus/atom-set-text/blob/master/spec/main-spec.js
- https://github.com/ben-eb/atom-cssnano/blob/master/spec/cssnano-spec.js

**Comment by florianb** [comment]
We then should probably also include support for Travis and Appveyour.

**Comment by sindresorhus** [comment]
I think Travis is enough. Even Atom doesn't yet test on AppVeyor and AppVeyor is just too unstable and bad. See: https://github.com/sindresorhus/atom-set-text/blob/master/.travis.yml

**Comment by florianb** [comment]
Good point -- i just thougt it could be a good idea testing it on windows since there might be differences due to the handling of line-endings.

**Comment by sindresorhus** [comment]
@florianb Yup. Can consider it in the future when Atom has battle-tested it.

**Comment by florianb** [comment]
The tests should include fixtures for:
- [ ] empty projects (#67)

**Comment by Arcanemagus** [comment]
FYI: Atom doesn't test on AppVeyor because it's near impossible to build on Windows properly :stuck_out_tongue:

There is a recommended CI configuration for AppVeyor that works quite well though, which can be found here: https://github.com/atom/ci

**Comment by florianb** [comment]
Hmmm - the build-script for OSX seems to apply atom into the project-directory letting xo complain about the style: https://travis-ci.org/florianb/atom-editorconfig/jobs/120570253

:bulb: Exclude the ./atom/-dir from the xo-searchpath?
:bulb: Change the buildscript?

**Comment by sindresorhus** [comment]
> Exclude the ./atom/-dir from the xo-searchpath?

:+1:

**Comment by florianb** [comment]
Thanks everybody for support! :beers:
