### ISSUE TITLE
Slight roadmap with milestones?

### ISSUE THREAD

**Issue by florianb** [sindresorhus/atom-editorconfig#73]
Since we're starting going on as a little team, i would like to start putting up milestones to cut upcoming work in smaller pieces and let everybody know what we're working on and when a release may be expected.

I could imagine
1. to file milestones naming the rising version
2. to let us discuss a milestone within its milestine-thread
3. to **not** set a milestone-date to lower the pressure

I'm filing this issue for discussion and i appreciate any feedback ( :+1: :-1: :memo: ) to let us finally decide if we're going to start using milestones.

**Comment by slang800** [comment]
feel free to make milestones... I mostly just work on a per-issue basis, but I'm cool with whatever helps you organize.

**Comment by florianb** [comment]
Thanks @slang800 - great!
Feel always free to intervene or get in touch if you feel uncomfortable with whatever i do. :pray:

Since all maintainers agreed and there were no objections against it, milestones are officially activated! :rocket:
