### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by florianb** [sindresorhus/atom-editorconfig#74]
I would like set Contribution Guidelines up, to help us to commit on some basic rules. @sindresorhus already pointed these guidelines out:

> The guidelines are simple. Be kind to everyone. Larger changes should come in a pull request. Smaller ones can be committed directly. Follow the existing code style (Tip: $ xo --fix can fix many issues) and ensure npm test passes before pushing a commit. You can use branches in this repo, but clean them up afterwards. I like a clean commit history, so when merging a pull request, either ask the contributor to squash their commits or do it for them manually.

There is only one thing i'd like to add: assign yourself to the issue you're working on, to avoid doubled work.

I guess writing this down in a dedicated file will also help new contributors to step in. Hopefully.

---
Todos:
- [x] Adjust guidelines to meet pending Tests (see #76)

**Comment by Arcanemagus** [comment]
That's what `CONTRIBUTING.md` is for :wink:.

**Comment by florianb** [comment]
Thanks @Arcanemagus.

If there are no objections form anybody, i'll set them up in the next days.

**Comment by sindresorhus** [comment]
Go ahead.

**Comment by florianb** [comment]
I created a first draft - i'll merge it after 48hrs of freedom:

https://github.com/florianb/atom-editorconfig/blob/iss74/.github/CONTRIBUTING.md

**Comment by florianb** [comment]
@sindresorhus: in the project settings, you might disable merge-commits & allow squash-commits only. I guess this avoids merge-clutter at all.

**Comment by sindresorhus** [comment]
> in the project settings, you might disable merge-commits & allow squash-commits only. I guess this avoids merge-clutter at all.

Already done.

**Comment by sindresorhus** [comment]
@florianb Looks good. Can you do some simple issue and PR templates that tell the user to read the contributing guidelines? https://github.com/blog/2111-issue-and-pull-request-templates And use lowercase filenames.

**Comment by florianb** [comment]
Aye.. :+1:

**Comment by florianb** [comment]
@sindresorhus: done, unfortunately i currently see no good use for the issue-template. We have two cases how bugs may be files, with use of Atom's exception reporter and by hand.

The first case is easy, it provides us with all necessary platform information on that bug. I the second case there are no "easy" commands which would collect all necessary information to debug unexpected behavior to include in the issue.

Sure, we could write something like "be explicit, if you face unexpected behavior try to explain what happens and what you expected instead". I don't know if this is something we have to explicitly write down?!

https://github.com/florianb/atom-editorconfig/tree/iss74/.github

**Comment by florianb** [comment]
Contribution-docs and templates are merged in - thanks for support everyone! :candy:
