### ISSUE TITLE
Add fine grained xo-config for specs-directory

### ISSUE THREAD

**Issue by florianb** [sindresorhus/atom-editorconfig#75]
Xo is configured to ignore the upcoming specs-folder (see #72 ). It would be more consistent if there would exist a fine-grained xo-config for the specs by explicitly allowing undefined variables or explicitly whitelisting the "globals" of Jasmine and Atom.

**Comment by sindresorhus** [comment]
> explicitly allowing undefined variables

Why would you want that?

> explicitly whitelisting the "globals" of Jasmine and Atom.

Done: https://github.com/sindresorhus/atom-editorconfig/commit/99e58fda79a1c7cb4094db08223dc362ab1b29e1#diff-ef549221cd1abd468ee7ae1769955dfdR2

**Comment by florianb** [comment]
Great - i didn't know anything about eslint-environments!
