### ISSUE TITLE
SoftTab-setting not working properly

### ISSUE THREAD

**Issue by florianb** [sindresorhus/atom-editorconfig#81]
This issue is a meta-issue to protocol and order the debug-process around the issue and join issues which are likely being related to this bug.

Any feedback, help, or suggestion is very appreciated. This issue is from now on the main place to discuss any related topics. This is also the staging area for Atom-related bugs which i will file after getting some feedback.

## 🐛 Related Bugs/Issues

- Setting the `indent_style` via `.editorconfig` is **not** or only partial **working**.
- The SoftTab-setting falls sporadic back to `true` (using spaces).
- Initially open Files when launching Atom always use SoftTabs.

#### 2.1. The `TextEditor.softTab`-setting may be overriden by a third-party package

This case couldn't be confirmed yet.

#### 2.2 The SoftTab gets also set by `TextEditor.handleTokenization()`

I currently do not know why and when `handleTokenization()` is being called, if it is [called](https://github.com/atom/atom/blob/master/src/text-editor.coffee#L3192) it always falls back to [SoftTabs](https://github.com/atom/atom/blob/master/src/text-editor.coffee#L2660) if the `tabType` is set to `auto`.

I consider this being a potential bug in Atom.

#### 2.3 The SoftTab gets also set by the `editor.tabTypeSubscription`

This is getting called if the general Atom-config setting for the `tabType` is being changed.

#### 2.4. The `TextEditorElement.buildModel()` initializes the TextEditor with soft tabs

This instantiation hardcodes the SoftTab to be `true`. Even though i currently don't know exactly how the `TextEditorElement` plays with the `TextEditor` do i assume that the `TextEditor` is set to SoftTabs when it gets displayed the first time, from deserialization or caching.

I consider this being a potential bug in Atom.

## 🚦 Solving Strategies

1. 🆙 Initiate the debug process for potential issues related to the Atom-project.
2. ~~🐒 Create a monkeypatch to make at least a little bit working: the SoftTabs would be set properly after reopening Editors which where still open after Atom launch.~~

I am sure i would like to upstream these findings to fix the probably wrong TextEditor behavior.

~~I am not that sure about the monkeypatch. I did already some tests and of course i can easily override functions (in the case of `handleTokenization` i consider the patch as harmless). But it will still need a reopening of the specific Editor which is annoying.~~

~~What do you think?~~

**Comment by mven** [comment]
Found my problem: `Preferences > Settings > Tab Type` was set to `hard` for some reason (by default maybe?). Once I set it to `auto`, editorconfig is now setting `softTabs` properly.

**Comment by florianb** [comment]
@mven - i'm glad you can work. I have to add that

### Setting "Tab Type" to "auto" is seems to be only an interim solution

As far as i know is the Tab Type "auto" only working if the given file already uses the preferred Tab Type. So if you f.e. decide within a spaced file to switch to tabs i made the experience that this may work for a few lines but Atom falls back to the *main* tab type.

However - this isn't confirmed yet (which is something i'll work on soon).

**Comment by mven** [comment]
I see what you mean. I'll try to run some tests too to confirm this.

**Comment by sindresorhus** [comment]
@florianb Can you open issues on the Atom issue tracker regarding the bugs you mentioned? And link to them from here.

**Comment by florianb** [comment]
@sindresorhus yeah, as soon as i have time to test the functionality on Atom. I want to get sure before opening the issue.

**Comment by florianb** [comment]
Okay, the bug is filed at https://github.com/atom/atom/issues/11611 - i hope it gets attention.

**Comment by florianb** [comment]
Okay - it seems i was barking up the wrong tree. I am really sorry for that confusion and i'm happy i got even more understanding about the processes handling the softTabs-settings.

I turned out, that it is absolutely necessary for editorconfig, that the config-setting `tabType` of Atom is set to `auto`.

I therefore would like to recommend to introduce a notification which warns about a wrong set setting if a user opens a file whose tab-setting is affected by editorconfig **and** the editorconfig-based tab setting contradicts to the Atom-configuration.

**Comment by florianb** [comment]
Closed in favor of #89
