### ISSUE TITLE
Update all open Editors after changing the .editorconfig

### ISSUE THREAD

**Issue by florianb** [sindresorhus/atom-editorconfig#85]
That would allow the user to change the .editorconfig without reopening files in order to make editorconfig work.

Instead (or in addition) of an autonomous update a command may be provided to let all editors become updated.

**Comment by Arcanemagus** [comment]
Maybe register an `onDidSave` handler that checks the file name and if it's `.editorconfig` it updates all open editors in the project that file belonged to?

**Comment by florianb** [comment]
This is for sure possible in an asynchronous and comfortable way.

💭 I would even consider watching all `.editorconfigs` in the project (using https://atom.io/docs/api/v1.7.3/File).

**Comment by Arcanemagus** [comment]
Ooo, didn't know about that API, nice!
