### ISSUE TITLE
Allow editorconfig to modify tabs accordingly to the settings?

### ISSUE THREAD

**Issue by florianb** [sindresorhus/atom-editorconfig#86]
This would easy the migration of a project to a new editorconfig-settings.

Probably that should be done explicitly by invoking a command, the changes should then be summarized in a proper way and being explicitly accepted or declined by the user.

Changes to the encoding, line-endings would be possible, too.

**Comment by Arcanemagus** [comment]
The whitespace package already implements this, and as it's a command that the user explicitly runs they will know what caused any changes, and can just use the undo functionality built into Atom to undo any unwanted change so I don't think a "confirmation screen" would really be necessary here.

**Comment by florianb** [comment]
A good point, thanks @Arcanemagus.

💭 if #87 would be realized the notification could contain a button or link to invoke that command. The whitespace-package is anyway part of the Atom-core-package, isn't it?

**Comment by Arcanemagus** [comment]
Correct, it's part of Atom core, although a user _could_ disable it for some bizarre reason.

**Comment by eddiemonge** [comment]
The tab type option should maybe have an "editorconfig" option or something. It doesn't really seem to follow editorconfig settings

<img width="879" alt="tabtype" src="https://cloud.githubusercontent.com/assets/127535/16737977/998c9dc4-4748-11e6-9dbc-66ee47aeba3a.png">

**Comment by Arcanemagus** [comment]
That option is part of Atom core, you can't change it...

**Comment by florianb** [comment]
Fun fact: You must disable the whitespace-package in order to make trim_trailiing_whitespace and insert_final_newline work.

However i will keep this functionality in mind, when eventually providing an autofix-button.

**Comment by florianb** [comment]
An introduction of `EditorConfig: Fix File` is pending.
