### ISSUE TITLE
doesn't work yet.

### ISSUE THREAD

**Issue by Amanda119** [sindresorhus/atom-editorconfig#88]
I am a nice person filing an feedback, idea or issue! :heart:

Because I'd like you to take a look on the following unexpected behavior, I...

- [ ] provide a list of installed packages (try `apm list`),
- [ ] provide possibly involved `.editorconfig`-files,
- [ ] described exactly which behavior was **expected** and **what happened** instead and
- [ ] send you some virtual :candy: to make you happy.

```
Mobile-friendly · indent_size = 4: end_of_line = lf: charset = utf-8: trim_trailing_whitespace = true: ... false # insert_final_newline = true ... EditorConfig - Atom https://atom.io/packages/editorconfig indent_style; indent_size; charset ... utf-8, utf-16be, utf-16le) end_of_line (supported values: lf, crlf) ... insert_final_newline = true # doesn't work yet.
```

**Comment by florianb** [comment]
@Amanda119 thank you for posting an issue - could you please be a little bit more specific about what you did expect and what happened instead?

**Comment by florianb** [comment]
🔔 @Amanda119 - i am going to close that issue to keep our backlog clean. I will reopen this issue as soon as you provide further information about your issue.

Thank you for contributing! 👍
