### ISSUE TITLE
Notify the user if the editorconfig is working im/properly

### ISSUE THREAD

**Issue by florianb** [sindresorhus/atom-editorconfig#89]
atom-editorconfig should:

- [x] notify the user if `config.tabType` prevents editorconfig from controlling the tab-types in the current editor

This might be done by a simple notification or as a less disturbing gui-icon 🐭 , showing different states like:

- not affected by editorconfig (the plugin is running, a editorconfig-file is present but the current file is not affected by any rules)
- conformal (editorconfig is controlling the current file, the file seems conformal to the applied rules)
- non-conformal (editorconfig is controlling the current file, but the file yet not conformal to the applied rules [f.e. mixed tab-characters]
- non-working (editorconfig should control the current file, but any environmental influence prevents editorconfig to work properly)

I personally tend to introduce a little gui-icon (probably a 🐲 ?), since it is much less disturbing than hitting the mind with notifications all the time.

**Comment by ttsda** [comment]
It could also work by adding a colour or icon to the editorconfig in the directory tree.

**Comment by florianb** [comment]
That's a good idea @ttsda - i guess implementing that would need to rearrange a lot of things to make it work properly.. i have to think about that.. 💭

**Comment by polarathene** [comment]
I'd rather not rely on colour of the icon, how does that affect icon themes or packages like git that can change the colour of icon/text? It would not be immediately obvious to me if I have a large project that I'm adding the file to which is the case for me right now for process improvement.

A notification warning/error on top right like other packages do would be preferred. Let me know that editorconfig expects a setting to work when I have an unsupported setting such as tab. Alternatively status bar at bottom of editor might be another location to indicate editorconfig in use or warning issue.

**Comment by florianb** [comment]
Good point @polarathene, maybe adding a overlayed icon to the project drawer's file icons would be a good idea. It would at least allow to recognise any problems at a first view.

Adding an indicator to the status bar is in any case a proven way to show the package status.

**Comment by florianb** [comment]
#95 belongs to the unintentionally wrongly set `tabType`.

**Comment by nckappeler** [comment]
In my opinion the tabType setting (as well as other editorconfig-settings) should always override the editors default settings (if different). The notification should the notice the user, that his default settings is ignored.

**Comment by florianb** [comment]
I completely agree @nckappeler, unfortunately Atom does not allow to override that setting in the Editor-Instance. We did not consider changing the global Atom-setting because it would result in many unwanted side-effects.

**Comment by crucialfelix** [comment]
Ah hah. So `Settings (main) > Tab Type` must be `Auto`. Otherwise atom-editorconfig cannot set the tab type at all. `editor.setSoftTabs(false);` does nothing.

Notwithstanding more elaborate solutions, this should be on the main README and in the config settings for atom-editorconfig. 

It's the most essential use of atom-editorconfig: to set your tab type based on file type. It appears to simply not work.

Also you could check the main config and if tabType is not auto then post to console.

I had to open up the plugin and put in debugging statements to figure out why this doesn't work.

**Comment by florianb** [comment]
Thanks for your feedback @crucialfelix: for a quick win i'll add a hint to the Readme, in mid-term atom-editorconfig should be able to show its state to the user (in one way or another).

**Comment by crucialfelix** [comment]
Exactly, do the quick win first. Thanks for working on this !

**Comment by vutran** [comment]
I like this idea. How about just a status icon in the status bar?

**Comment by FezVrasta** [comment]
I have EVERYTHING set to auto, but it still doesn't work on JavaScript files.

To note that I have `babel-language` installed, but its tabs settings are set to auto as well...

**Comment by florianb** [comment]
@FezVrasta thanks for getting in touch. Atom-editorconfig should -- besides of a probably explicitly set tab-type -- work pretty stable. Please open a new issue and don't forget to attach your packages-list as well as your editorconfig-file.

**Comment by FezVrasta** [comment]
https://github.com/sindresorhus/atom-editorconfig/issues/103

**Comment by florianb** [comment]
Happy News! 🎉 

![image](https://cloud.githubusercontent.com/assets/983507/19517990/cabdc250-9604-11e6-93ce-0732695df9db.png)

Although i am not happy with the Icon.. it would be nicer to have a small 🐭  there. Oh and of course the Tab Type issue is addressed, too.
