### ISSUE TITLE
Support ALL EditorConfig Properties

### ISSUE THREAD

**Issue by florianb** [sindresorhus/atom-editorconfig#90]
In a galaxy far far away\* atom-editorconfig supports all [EditorConfig Properties](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties):
- [x] `indent_style`
- [x] `indent_size`
- [x] `tab_width` (faulty implemented: #91)
- [x] `end_of_line`
- [x] `charset`
- [x] `trim_trailing_whitespace`
- [x] `insert_final_newline`
- [x] `max_line_length`

*) this may happen never, but i need to track that down!

**Comment by nixel2007** [comment]
@florianb i've made a PR with implementation of two missing properties. i think, you'll be interesting for you.

**Comment by Julian-B90** [comment]
Hello give it any updates with trim_trailing_whitespace?

**Comment by florianb** [comment]
I am currently playing around with different approaches to solve that - i will try to finish that work in the next weeks.

**Comment by florianb** [comment]
Releasing #106 to the wild -- expect trim_trailing_whitespace & insert_missing_newline to come.

**Comment by florianb** [comment]
🎺 The implementation of `max_line_length` is pending. I would appreciate any help testing it *before* we're releasing it: #123 (instructions can be found in the PR-description).

**Comment by florianb** [comment]
I would like to make the next release a major-release to reflect the maturity of the package.

/cc @sindresorhus, @slang800, @eddiemonge
