### ISSUE TITLE
atom-editorconfig seems to ignore newline setting in existing files

### ISSUE THREAD

**Issue by Thanood** [sindresorhus/atom-editorconfig#93]
I am a nice person filing an feedback, idea or issue! :heart:

Because I'd like you to take a look on the following unexpected behavior, I...

- [x] provide a list of installed packages (try `apm list`),
- [x] provide possibly involved `.editorconfig`-files,
- [x] described exactly which behavior was **expected** and **what happened** instead and
- [x] send you some virtual :candy: to make you happy.

Nice template. :smile: 

With the current stable Atom version (1.8.0) and editorconfig (1.4.1) I'm missing a convenient behaviour that has been working until the latest update.

My `npm` and `jspm` insist to insert `crlf` newlines but my `.editorconfig` says `lf` and so does my git repo which always leads to (from the point of view of git) whole files changed instead of just a line.

**Expected**:
Previous versions detected this deviation when I opened the file, changed the newlines to `lf` and set the buffer to `dirty` for me to save.

**What happened**:
The current version doesn't do that.

My `.editorconfig`:

```
# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true

# 2 space indentation
[**.*]
indent_style = space
indent_size = 2
```

Installed packages:

```
Community Packages (70) C:\Users\danielb\.atom\packages
├── atom-beautify@0.29.8
├── atom-material-syntax@0.4.6
├── atom-material-ui@1.2.13
├── atom-notifier@0.5.0
├── atom-typescript@8.11.0
├── autoclose-html@0.23.0
├── autocomplete-json@5.0.3
├── autocomplete-modules@1.5.1
├── autocomplete-paths@1.0.2
├── blessed-light-syntax@0.3.0
├── bottom-dock@0.4.4
├── build@0.64.0
├── build-gulp@0.11.0
├── busy@0.5.0
├── ctrl-last-tab@0.3.0
├── daylight-ui@0.2.2
├── editorconfig@1.4.1
├── electron-light-syntax@1.2.0
├── file-icons@1.7.15
├── file-types@0.5.1
├── fizzy@0.16.0
├── format-sql@0.3.0
├── genesis-syntax@1.0.7
├── genesis-ui@0.5.0
├── gist@0.3.1
├── gist-it@0.9.1
├── git-control@0.7.1
├── git-plus@5.15.0
├── github-notifications@0.1.2
├── gulp-manager@0.2.19
├── highlight-selected@0.11.2
├── image-copipe@0.3.1
├── isotope-light-ui@2.2.6
├── isotope-ui@2.7.1
├── js-refactor@0.6.0
├── jsformat@0.9.3
├── keyboard-localization@1.4.18
├── language-aspx@0.4.0
├── language-batch@0.3.3
├── language-cshtml@0.2.1
├── language-jade@0.7.1
├── language-javascript-jsx@0.3.7
├── language-lua@0.9.4
├── language-patch@1.2.0
├── language-powershell@2.1.1
├── linter@1.11.11
├── linter-eslint
├── linter-sass-lint@1.6.0
├── linter-stylelint@2.12.0
├── linter-stylint@2.1.2
├── markdown-scroll-sync@2.1.2
├── mdl-snippets@0.3.0
├── metro-syntax@0.3.1
├── metro-ui@2.2.2
├── minimap@4.24.6
├── multi-cursor-plus@1.0.1
├── naturezen-light-syntax@0.1.0
├── northem-light-atom-syntax@0.19.1
├── northem-light-atom-ui@0.4.0
├── octocat-syntax@0.1.5
├── project-manager@2.9.7
├── project-sidebar@1.3.0
├── refactor@0.6.0
├── solarized-dark-ui@0.3.1
├── solarized-light-ui@0.1.0
├── sort-lines@0.14.0
├── Stylus@3.0.0
├── sync-settings@0.7.2
├── travis-ci-status@1.1.1
└── xml-formatter@0.10.0
```

And finally the candy I promised: :candy: :candy: :candy: 

Thanks for any help. :smile:

**Comment by florianb** [comment]
Hi @Thanood - thanks a lot for getting in touch! 😄 

Actually the "functionality" you're missing was dropped with 07f94f0f83429057c581ffc5881542e8d24e6e4e, since it was **not** compliant to [editorconfig.org](https://github.com/editorconfig/editorconfig/wiki/FAQ#my-files-are-not-automatically-reformatted-the-editorconfig-plugin-is-not-working):

> Existing files are not reformatted. Only newly input lines are formatted in the format given in the .editorconfig files.

If you enjoyed using atom-editorconfig to reformat line-endings i am very sorry that we interrupted your workflow. 🍰 

I would like to suggest you taking a look on the built in functionality of Line Ending Selector (`shift-ctrl-p` + `les`).

Since i don't feel i could help you by reenabling the transformation in this plugin i would like to ask if i understood your problem correctly and if i answered your question. If so i would like to close this issue - if you feel we could improve atom-editorconfig somehow else dedicated to this issue, please let me know! 😁

**Comment by Thanood** [comment]
Thanks for your response, @florianb. :smile: 
I appreciate the clarificaton of the topic since I didn't know that it's not compliant. That's (of course) okay for me. I like standards.

As a last comment I would like to tell you that you have understood my problem correctly and you indeed helped me by referring to the editorconfig FAQ. Thank you.

Please feel free to close this issue.

Schöne Grüße aus Köln. :wink:

**Comment by florianb** [comment]
Ha! Danke -- beste Grüße aus Berlin! 😄 🍻
