### ISSUE TITLE
indent_style setting ignored

### ISSUE THREAD

**Issue by nckappeler** [sindresorhus/atom-editorconfig#95]
The indent_style setting is ignored, it always inserts spaces. Other settings like indent_size are working as expected.

Atom: 1.8.0
OSX: 10.11.5 

Plugins:
<pre>
├── atom-autocomplete-php@0.18.9
├── atom-beautify@0.29.7
├── autoprefixer@3.2.0
├── color-picker@2.1.1
├── compare-files@0.6.2
├── docblockr@0.7.3
├── editorconfig@1.4.1
├── file-icons@1.7.13
├── gitignore-snippets@0.2.5
├── highlight-line@0.11.1
├── highlight-selected@0.11.2
├── hyperclick@0.0.36
├── javascript-snippets@1.2.1
├── keybinding-cheatsheet@0.1.0
├── language-jade@0.7.1
├── language-mongodb@0.3.1
├── linter@1.11.4
├── linter-eslint@7.2.2
├── linter-jade@0.3.2
├── linter-php@1.2.0
├── markdown-pdf@1.5.0
├── merge-conflicts@1.4.3
├── native-ui@0.18.2
├── php-getters-setters@0.5.5
├── php-hyperclick@1.0.0
├── php-integrator-annotations@0.4.1
├── php-integrator-autocomplete-plus@0.8.1
├── php-integrator-tooltips@0.6.1
├── pigments@0.29.1
├── react@0.15.0
├── rest-client@1.1.1
├── todo-show@1.6.0
└── typo3@0.7.0
</pre>

.editorconfig
<pre>
root = true

[*]
indent_style = space
indent_size = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.{js,json}]
indent_size = 2

[*.{php,ts,xlf,xml}]
indent_style = tab

[makefile]
indent_style = tab
</pre>

**Comment by nckappeler** [comment]
OK my bad, I had configure my atom to insert soft-tabs (option: "soft") in Settings > Editor Settings > Tab Type
changing it to "auto" solved to problem for my.
Maybe you could note that in the readme.

**Comment by florianb** [comment]
Thanks for your feedback @nckappeler -- ❤️

**Comment by rizkysyazuli** [comment]
@nckappeler thx for the tip.

does anyone care to explain why is this happening? coz it kinda beats the purpose of using editorconfig if i still have to tell my team mates to tweak their editor settings.

**Comment by florianb** [comment]
@rizkysyazuli -- Atom enforces the given tab-setting not letting us to override it reliable if set to anything else then "auto". We plan to integrate some kind of notification for that case.

**Comment by rizkysyazuli** [comment]
@florianb noted. thx.

**Comment by deitch** [comment]
@florianb I still am struggling with this. Sometimes it works, sometimes not. My `.editorconfig` is straightforward, basically soft-tabs for everything except Makefile:

```ini
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true

# 2 space indentation
[**.*]
indent_style = space
indent_size = 2

# makefile
[Makefile]
indent_style = tab
```

And yet it seems random as to when I get it to insert tabs, when spaces. I tried with my Atom settings both auto with "Soft Tabs" checked and unchecked. 

Is there a way to debug it, to get editorconfig package to tell what it is doing? More than happy to help contribute to debugging if I can know how to get it to tell me.

**Comment by florianb** [comment]
@deitch - thank you very much for reporting this! You can check atom-editorconfig's applied settings with the "EditorConfig: Show State" command.

Since we made a lot of changes to the package internals i'd like to ask you opening a new issue for this, including all necessary information (described in the template). Thank you very much in andvance! 🌷

**Comment by deitch** [comment]
@florianb thanks. That is very helpful. As I said before, it seems somewhat random. As soon as I have it reproduce, I will use the `EditorConfig: show state` command to grab it and open a new issue.
