### ISSUE TITLE
Fails to install on ubuntu 16.10 64 + atom 1.8.0

### ISSUE THREAD

**Issue by rerodrigues** [sindresorhus/atom-editorconfig#97]
Hi, I'm trying to instal this package on a clean ATOM 1.8.0 installation, running on a Ubuntu 16.04 64bits machine.

The following error happens both, using apm or the Install packages screen

```
Installing “editorconfig@1.4.1” failed

gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | linux | x64
gyp http GET https://atom.io/download/atom-shell/v0.36.8/node-v0.36.8.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: tunneling socket could not be established, statusCode=502
gyp ERR! stack     at ClientRequest.onConnect (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:163:19)
gyp ERR! stack     at ClientRequest.g (events.js:180:16)
gyp ERR! stack     at ClientRequest.emit (events.js:106:17)
gyp ERR! stack     at Socket.socketOnData (http.js:1613:11)
gyp ERR! stack     at TCP.onread (net.js:528:27)
gyp ERR! System Linux 4.4.0-28-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.36.8" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /home/renato/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
```

I don't know if it only happens on my machine, but upgrading my packages didn't helped.

Thanks a lot!

**Comment by rerodrigues** [comment]
Just to compliment, yes, it can be something with my machine. I've just installed it on my home machine running the same Atom 1.8.0 on Windows 10 Home 64 bits and worked fine.

I was not able, however, to figure out what was causing the error on the linux machine.

**Comment by florianb** [comment]
Hi @rerodrigues - thanks for getting in touch. I believe this issue belongs not to atom-editorconfig. I'd like to refer you to this npm-issue: https://github.com/npm/npm/issues/2472
It seems like they're discussing your problem and find different potential solutions.

I will close this issue for now. If you're able to find any hints that this package may cause this issue, please feel free come back.
